### ISSUE TITLE
graceful shutdown method

### ISSUE THREAD

**Issue by mcosmin222** [ffmpeginteropx/FFmpegInteropX#103]
So i have been thinking the other day, while trying to implement some real time coms system using this MSS (with a custom InputStream), what if we had a "SignalToStop" method? This will cause the next sample requests to return null samples, thus signaling end of stream? 

This is really more uaeful in advanced scenarios where errors/exceptions theown by MF would cause latency issues. 

It is pretty straight forward to implement, just requires a bool and an if in sample request.

What do you think?

**Comment by lukasf** [comment]
Is there really such a big delay (if no debugger is attached)? What about just setting a null source on the MediaElement instead?

But yeah, it could easily be added, I don't see any problems there. So if you think this is an improvement for your scenario, feel free to create a PR.

**Comment by mcosmin222** [comment]
Cool. I will add it after I do some more testing.

**Comment by mcosmin222** [comment]
Not needed.
