### ISSUE TITLE
extracting metadata tags from media

### ISSUE THREAD

**Issue by mcosmin222** [ffmpeginteropx/FFmpegInteropX#105]
I think it is possible to extract metadata tags from media files. Should we add this functionality to the library?

**Comment by lukasf** [comment]
Do you mean to show tags of a loaded file, or do you want to provide a specialized tag parser class?

Just now I think, if we'd use ffmpeg for music streaming, then we would also need a way to show metadata (e.g. current title) from that stream. That kind of metadata comes during playback. Not sure where we can access that from ffmpeg (but there sure is a way). But this is probably not the scenario you had in mind.

**Comment by mcosmin222** [comment]
Not really that advanced. I was thinking of IDv3 tags from mp3 for example. But I see you are bringing the idea to a whole new level ^^

**Comment by mcosmin222** [comment]
I will start working on this. Basically the plan is simple: expose the metadata avdict for each streaminfo object.
