### ISSUE TITLE
Play .vob DvDSub subtitle error

### ISSUE THREAD

**Issue by sudongg** [ffmpeginteropx/FFmpegInteropX#108]
Hi, @lukasf 
When I play some .vob files, I get an error at some time. After playing with potplayer, I found that there is bitmap subtitles, but ffmpeg does not detect subtitles.
Here is the sample file:
https://www.dropbox.com/s/3bludytyp4j9xxo/The%20Cranberries%20-%202002%20-%20Stars.zip?dl=0
There will be an error when playing to the 10th second, I tried to disable video or audio, the problem is still

**Comment by lukasf** [comment]
Hi @sundongg,
the problem with VOB files is that they do not have a file header, so streams can appear later in the file, and then we are not prepared for that. We have a check for the stream index for that exact case, but it has a bug, so the app crashes.
It will be easy to fix the crash. But we are

**Comment by sudongg** [comment]
Thanks @lukasf ,
Will not crash after repair, but will stop playing

**Comment by lukasf** [comment]
Oh, I did not checkin the complete changes. Please try with newest changeset, it should play the file fine until end.
