### ISSUE TITLE
Sometiems audio has low(er) volume

### ISSUE THREAD

**Issue by brabebhin** [ffmpeginteropx/FFmpegInteropX#110]
Hello @lukasf ,

I have been bothering with an issue that always seems to escape me. Sometimes, some video files contain audio streams in which the volume of the actors is very low compared to say, background sounds or even music.

This is annoying sometimes because I can hardly hear them. When I play the same file in the default video app, the volume is much more balanced. This seems to happen usually with aac encoded audio.

I figured the default app must be using some sort of loudness equalization, I tried various filters from ffmpeg library but none seem to quite cut it. Did you encounter something similar yourself? Does my story actually make any sense?

**Comment by lukasf** [comment]
Hi @mcosmin222, I assume you are listening with stereo speakers? A small google search got quite a bunch of results where people report this, and mostly it was related to AAC 5.1 audio in MP4 container, played on stereo setup. I remember that I had this myself a few years back (can't say which file formats). I think I solved it by manually configuring the 5.1 downsampling in MPC-HQ back then.

Right now I guess that it is caused by incorrect detection of 5.1 multichannel audio. Maybe ffmpeg chooses a wrong downsampling method, so the center channel does not get mapped correctly to left/right.

Can you upload a sample file?

**Comment by mcosmin222** [comment]
I will look for a file. Good catch about resampling 5.1. i typically fix this by enabling loudness equalization in audio driver settings, so I assumed it had something to do with that and digged in that direction. 

I will try to upload a file without changing this behaviour.

**Comment by mcosmin222** [comment]
Here's the test file: 

https://1drv.ms/u/s!Ao-WOwsImxSMt5UtwPB6-Cp7Pcn7Gw?e=vpipwU

You can play it with our sample and with movies+TV on a stereo system and you will notice the movies+TV is around twice as loud.

**Comment by mcosmin222** [comment]
Anyway, I will dig more into this this week, I will have more time :)

**Comment by mcosmin222** [comment]
Strangely enough, I cannot reproduce this on my dev machine. Only on the "entertainment" machine, which happens to have a pair of bluetooth audio speakers. I wonder if somehow the system reports the wrong channel layout.

**Comment by lukasf** [comment]
I just tried the download link, and it does not work for me.

It is strange that it does not happen on your other PC. Both have stereo output? Is AAC passthrough enabled or disabled? If passthrough is disabled, I would also assume that this is a problem with the channel layout. You sould check input and output channel layout of the audio sample provider, and compare it with a "normal" 5.1 file.

**Comment by mcosmin222** [comment]
The link expired.

**Comment by mcosmin222** [comment]
https://1drv.ms/u/s!Ao-WOwsImxSMt5UtHAFflknggvBD8w

Try this one.

**Comment by lukasf** [comment]
The problem cannot be reproduced on my side. All players show the same volume level. 

But while testing, I found out something strange: All 5.1 files I tried will have channel layout 0x60f, and for all of them, the output (default) layout chosen in our code will be 0x3f. The difference is that 0x60f will have the surround channels defined as "side left, side right", while 0x3f is defined as "back left, back right". Actually, side left/right is correct, it is also what other players will show as media info. Back left/right is used in 7.1 setups, not in 5.1 setups. It is strange that this is what ffmpeg returns as "default layout" for 6 channels.

I am not sure, but it might be that the resampler will try to somehow re-mix the channels. That's not a good idea. Instead, we should pass the channel layout information to MF. What's nice is that FFmpeg uses basically the same format for channel mapping as MediaFoundation:

https://docs.microsoft.com/en-us/windows/desktop/medfound/mf-mt-audio-channel-mask-attribute

https://www.ffmpeg.org/doxygen/3.2/channel__layout_8h.html

We'd just need to make sure that the ffmpeg value is not 0x20000000 or higher, then we can just keep the input layout and pass it on to MF. I am not sure if this would fix the problem for you, but I think this is the right way to handle channel layout.

**Comment by lukasf** [comment]
I created PR #111 to pass channel layout info to MF. Please try the branch "channel-layout" to see if this improves the volume levels for you.

**Comment by lukasf** [comment]
I also created a bug entry in ffmpeg bug tracker, because I think the default is wrong for 6 channels...

**Comment by mcosmin222** [comment]
Nice catch!

I will try it when i get home.
I gave it a few tests on Monday (i think) and also found the channel layouts values, but i wasn't aware of the difference between 5.1 and 7.1.  i just assumed 7.1 back left/right would map to 5.1 side left/right when 5.1 sound is passed through. Learned a new thing today.

 Thanks!

**Comment by lukasf** [comment]
I don't really know how a 7.1 file would map to 5.1. Either the back channels are left out, or they are mixed into the side left/right from the 5.1 setup. But here we have 5.1 files where the surround channels (side left/right) get mapped to the wrong position (back left/right). Not sure how that would be mixed back to "normal" 5.1. With my fix, there should not be any mapping or mixing.

**Comment by mcosmin222** [comment]
Sadly the volume thing is still not fixed but at this point I think it is a peculiarity of that machine. 
As I said, VLC also has a lower volume, I am pretty sure movies+TV does some audio processing. 
If I turn on loudness normalization from audio driver, then VLC and ffmpeg both have the same volume as movies+TV.

**Comment by mcosmin222** [comment]
This is indeed a problem of channel layout.
I think we should allow forcing audio to a specific channel layout through the Config file.
I tried it by forcing to stereo and the volume is indeed higher.

There can be other use cases for this as well, not just this particular issue, like forcing 5.1 setups when the audio is stereo and other similar tricks.

**Comment by villagra** [comment]
@mcosmin222 how do you force the audio channel layout? I'm facing the same issues with 7.1 audio tracks. The actors voices are way to low...

**Comment by lukasf** [comment]
Can you both provide samples of such files? There was a problem with the FFmpeg default mapping of 5.1, which we could fix. Maybe there are similar problems for 7.1 as well. Such a fix would automatically work for all files.

Sure we could also allow forcing a specific layout through the config file. Then we would also need to override the number of channels, right? Or maybe we can somehow infer that from the layout.

**Comment by mcosmin222** [comment]
@villagra, i essentially coded a new feature.

@lukasf 
FFmpegInteropX already does resampling when there is a difference between the output audio stream descriptor and the av codec context. The featureis quite minimal effort.

I will try to upload the file.

**Comment by villagra** [comment]
I'll try to find a file...i'm on "holidays" right now and can't access my usual test files from here

**Comment by mcosmin222** [comment]
My file is too big.
It has 5.1 audio (not 7.1)

In UncompressAudioSampleProvider::CreateStreamDescriptor

inChannels = 6
inChannelLayout  = 1551
outChannelLayout = 1551
inSampleRate = 48000
inSampleFormat = AV_SAMPLE_FMT_FLTP
outSampleFormat =AV_SAMPLE_FMT_FLT

**Comment by lukasf** [comment]
Can you try to extract the audio stream and upload it?

https://stackoverflow.com/questions/9913032/how-can-i-extract-audio-from-video-with-ffmpeg

**Comment by villagra** [comment]
Here is a test file:

https://1drv.ms/u/s!Ajg8AuGl0XTgqMgh1o7CGURuWL6AHA?e=z65lnB

Skip to the minute 1:15 when Frodo starts taking and you'll see how the actor's voice is practically missing.

**Comment by mcosmin222** [comment]
@lukasf 

Do you still need me to extract the audio stream? or is it @villagra  file enough?

**Comment by lukasf** [comment]
@villagra Thanks for reporting and sorry for the late investigation. Usually for multichannel audio streams, all sound contained in the center channel is also contained in left/right channels. But it turns out that for a few rare movies, the actors are only mixed into the center speaker and not into left/right (or only at extremely low volume). This is alright when listening on a multichannel system. But on a stereo system, things are different. Windows seems to assume that the center speaker is not required when downmixing to stereo, so the center channel is plain dropped.

In #220 I added a new option to downmix to stereo using FFmpeg mixer. FFmpeg will correctly mix the center speaker into the resulting stereo output. The provided file plays without any issues when enabling this.

**Comment by lukasf** [comment]
Hi @mcosmin222 can you test your 5.1 file with the new downmix option `Config.DownmixAudioStreamsToStereo` as well? It is available on master branch. The file from @villagra plays fine with it.

**Comment by lukasf** [comment]
I think this is solved with #220. Feel free to re-open or create new issue if problems still persist.
