### ISSUE TITLE
time out will not stop playing

### ISSUE THREAD

**Issue by sudongg** [ffmpeginteropx/FFmpegInteropX#116]
Hi @lukasf 
When playing some videos, the end of time does not stop and the time continues to increase.
Here is the sample file:
https://www.dropbox.com/s/6r8r1zh382rx3cc/2Pac%20-%20Pac%27s%20Life%20Ft.%20T.I.%2C%20Ashanti.vob?dl=0

**Comment by lukasf** [comment]
Hi @sudongg,

I am very busy this week. I will look into the file, but it might take some time. 

From what you write, I think this is a problem with the file and not a problem in the library. Sometimes ffmpeg cannot correctly detect the length of a file. Then the progress bar is already at end, but playback continues. We cannot do anything about that. The seconds thing that can happen is that the audio stream is longer than the video stream. Then the video stops at what is detected as end of file, but audio stream continues to play (silence or whatever). Also in that case, MF will continue playback until all streams have stopped.

**Comment by mcosmin222** [comment]
I gave this a test yesterday evening, using my own app which also uses this library. The duration is 3 minutes + or something, and it does indeed stop. Video goes black in the last seconds but playback eventually stops. 

The only strange thing i noticed was gpu usage skyrocketing at the end, but that might be unrelated.

**Comment by sudongg** [comment]
Hi @mcosmin222 
I use the master branch for sample testing, 
If you drag the progress bar to the end, it can end normally. However, the normal play to the end, the time is still increasing, and will not trigger the MediaEnded event.

**Comment by mcosmin222** [comment]
Strange. I will try again when I get back home.

**Comment by mcosmin222** [comment]
The sample stops at the end. There are like 3 seconds or so of silence at the end. Maybe I'm doing something wrong..

**Comment by sudongg** [comment]
@mcosmin222 
I use the latest master branch for sample testing, The filter branch has the same problem.
Passthrough Video is enabled by default and needs to be turned off, otherwise only audio will be played.

**Comment by mcosmin222** [comment]
Ah yes, if I set the passthrough to false, it indeed does no longer stop.

**Comment by sudongg** [comment]
@mcosmin222 
Thank you, The problem has been solved.

**Comment by sudongg** [comment]
@mcosmin222 
Thank you, The problem has been solved.

**Comment by lukasf** [comment]
@sudongg Can you share your solution with us? I think we should somehow check for invalid pts values (the question is how).

**Comment by mcosmin222** [comment]
What if we drop samples that have pts > duration?
Except for when duration is 0.

**Comment by lukasf** [comment]
I am not sure what you mean. Pts is an abstract position, it can start at arbitrary, even negative values. We can only compare it to the expected position (that is nextFramePts, calculated from previous pts + previous duration). It can happen that there are smaller or bigger gaps in frame positions, we should be graceful and continue playback. Only if the gap is really large, we should drop out.

**Comment by lukasf** [comment]
I just noticed one thing: The pts value you posted (hex: 0x7FFFFFFFFFDD25B1) is suspiciously close to AV_PTS_NOVALUE (0x8000000000000000). I am not 100% sure we are handling all corner cases correctly. I hope that I will have some more time next week, then I will further investigate.

**Comment by mcosmin222** [comment]
oh sorry, I meant that if the presentation timestamp of the sample is outside of the media duration, then we should consider the sample as invalid, and apply our usual algorithm for skipping over broken frames/packages.

Yes, you are right, about that value being very close to AV_PTS_NOVALUE, but searching for it doesn't yield anything.

**Comment by lukasf** [comment]
For some files, the duration can only be estimated by fffmpeg (e.g. missing or corrupt file header). We should not drop samples if the actual duration is longer.

We usually check for AV_PTS_NOVALUE, but maybe we forgot to add this check in some place. Then we would suddenly calculate with 0x8000000000000000 and might end up with the pts you posted. The values are just so close that I feel they are connected somehow, possibly by accident on our side.

**Comment by mcosmin222** [comment]
Hmm.
Maybe we should consider all pts < 0 as invalid and default to our calculation? We do a check against pts value being different than AV_PTS_NOVALUE but maybe for broken files this can come up as negative.

**Comment by sudongg** [comment]
@lukasf 
As mcosmin 222 said, because of encountering unreasonable pts value, the playback can not be stopped correctly.
So I use: 
if (pts > 100000000000000) pts = 0; 
To exclude unreasonable pts  value.

**Comment by lukasf** [comment]
@sudongg When playing web streams or stream capture files, pts can have very high values. It is probably not a good idea to discard such packets entirely. 

At least for the official solution in our lib, we should take into account the previous packet's pts, and then decide based on the delta.

**Comment by sudongg** [comment]
@lukasf 
Currently, the web stream has not been tested, but after a few days of testing, I found some crashes, I am not sure if it is caused by this pts check.
I don't think this is a good solution. Looking forward to a better solution.

**Comment by mcosmin222** [comment]
@sudongg please check PR and see if it fixes it for you (it did for me).

**Comment by sudongg** [comment]
@mcosmin222 , 
No problem after several sample tests. Thank you.
