### ISSUE TITLE
Metadata tags do not support UTF8 encoding

### ISSUE THREAD

**Issue by lukasf** [ffmpeginteropx/FFmpegInteropX#120]
FFmpeg will convert all text to UTF8, but the MediaMetadata class will parse keys and values as ANSI. This will cause problems with unicode tag values. I think all tag values, and maybe also the keys need to be parsed as UTF8.

**Comment by mcosmin222** [comment]
is this even possible? I looked up av_dict API, and it doesn't seem to support utf-8.

**Comment by lukasf** [comment]
It returns char*, which is basically just a byte array. We need to parse it like in the SubtitleProviderSsaAss::CreateCue function (and maybe check with a few files that it returns correct data).

**Comment by mcosmin222** [comment]
Do you have such a file? I am quite surprised the conversion doesn't happen already. But then again strings in C++ are quite a pain.

**Comment by lukasf** [comment]
The convert function you use assumes that strings are ANSI encoded, but ffmpeg uses UTF8. We need to explicitly use UTF8 conversion.

**Comment by lukasf** [comment]
I already have a fix. Here is a file. Title should be "Ausländer" but shows up broken in current version.

https://1drv.ms/u/s!Asy3bMoFN_qNh_dcl134zoqBlaviyw

**Comment by lukasf** [comment]
Fixed with #121
