### ISSUE TITLE
Video filter modification cannot be applied while paused

### ISSUE THREAD

**Issue by sudongg** [ffmpeginteropx/FFmpegInteropX#126]
Hi @lukasf
Thanks for adding the video filter.
But, Video filter modification cannot be applied while paused, How to apply modifications when paused?

**Comment by lukasf** [comment]
Hi @sudongg,

this is a known limitation of the IBasicVideoEffect API. The effects are applied as new frames are decoded. Once a frame was decoded, it will not be changed. There is no good way to work around this. You could seek the video to the exact same position on every change, this would cause the effect to be applied, but it would be very slow (depending on video codec and resolution).

@mcosmin222 tried to apply the effects on composition surface level, but I think he faced some problems with that. This would resolve the "apply on paused" issue, but it had its own pitfalls. Not sure how the status was on that.

**Comment by mcosmin222** [comment]
Hi,

You can apply the video filter on a composition surface just fine, however, it is not possible to apply subtitles, so I just dropped it altogether. It will also not be possible to stream the filtered video on a DLNA device. But as long as you don't need subtitles and you don't need to stream it, you will do just fine with composition surfaces.

If you go down this route, you will need to (re)implement a lot of the functionality of the Media(Player)Element. This may or may not be enough for you depending on your scenario.

**Comment by sudongg** [comment]
Hi @mcosmin222 
I use MediaPlayer + CompositionSurfaceBrush instead of MediaElement, how do I apply Video Effect on CompositionSurface?

**Comment by mcosmin222** [comment]
I deleted all code samples. But you can apply ui composition to achieve the same effects. Basically you need to apply a CompositionBrush to your surface.

You can apply most of the effects from IBasicVideoEffect implementation in a CompositionBrush. I think only tint is misding.

https://docs.microsoft.com/en-us/windows/uwp/composition/composition-brushes

https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.spritevisual

https://microsoft.github.io/Win2D/html/N_Microsoft_Graphics_Canvas_Effects.htm

**Comment by lukasf** [comment]
The downside is that you won't get subtitles with that approach.

**Comment by sudongg** [comment]
Hi @mcosmin222
I have implemented ColorMatrixEffect and TemperatureAndTintEffect on composition brush, but SharpenEffect cannot be applied to composition brush. Effects that can be applied to the composition brush are quite limited.
And after using MediaPlayer.SetSurfaceSize (such as setting to the entire window size), Effect will be applied to the entire window. This is not the effect I want.
I am going to give up the composition brush effect.

**Comment by mcosmin222** [comment]
The only other way is to have it applied via directx shaders, and use the media player in frame server mode. I didn't explore much in this direction though.
