### ISSUE TITLE
Support Visual Studio 2019

### ISSUE THREAD

**Issue by lukasf** [ffmpeginteropx/FFmpegInteropX#128]
The ffmpeg build currently fails when VS2019 is installed. I am working on getting VS2019 to build correctly...

**Comment by mcosmin222** [comment]
I don't event have it installed.
I wish they stopped breaking toolchains every new release.

**Comment by lukasf** [comment]
It was more a problem of the project files from the additonal libs (zlib, iconv and bzip2). They have some hand written conditions checking VS versions. Our library built just fine with VS2019 without any change.

**Comment by lukasf** [comment]
I like VS2019, it's again a lot faster and snappier, compared to VS2017...

**Comment by lukasf** [comment]
I got it working now with #129.

After pulling the changes, you need to run `git submodule update` to update all libs to latest version.

**Comment by lukasf** [comment]
Seems to work all fine now, closing this...
