### ISSUE TITLE
FFmpeg 4.2 released

### ISSUE THREAD

**Issue by lukasf** [ffmpeginteropx/FFmpegInteropX#130]
Most notably, it can decode the new AV1 format.

**Comment by mcosmin222** [comment]
Sounds interesting. I will give it a shot in the evening.

**Comment by mcosmin222** [comment]
building it now.....

**Comment by mcosmin222** [comment]
So the first file one tries gives off a catastrophic failure, but subsequent attempts will not have this problem.

**Comment by lukasf** [comment]
Have you used an official, tagged ffmpeg version, e.g. n4.2.0? I would assume that the version string only has a version number on tagged ffmpeg releases. Using "latest" might give unexpected results.

We should make sure though that we do not crash when an unexpected string comes (maybe just skip the check).

**Comment by mcosmin222** [comment]
I downloaded the source from their git. Maybe i made a mistake. But still, the docs for that function clearly says we shouldn't use it :(

**Comment by lukasf** [comment]
I am aware that we are not supposed to use that string, but there is no other way to get the overall ffmpeg version number. There are only APIs to query the version number of each submodule, but not the overall number.

We should just make sure that we do not crash when we encounter an unexpected number.

The best way to try a new ffmpeg version is to just use git bash in FFmpegInteropX root:
```
cd ffmpeg
git fetch
git checkout "n4.2.1"
```
Now the ffmpeg submodule is on the official "4.2.1" release (which should have a proper version string) and you can start building ffmpeg. You can browse the official release tag names on [ffmpeg github](https://github.com/FFmpeg/FFmpeg): Click on "Branch", then switch to "Tags", scroll down to tags starting with "n" (which is the new version tagging scheme).

To get back to the original ffmpeg version, as defined in our lib, go back to parent folder and update submodules:
```
cd ..
git submodule update
```
Now you are back on our original ffmpeg version.

**Comment by mcosmin222** [comment]
You are right. For some reason i didn't have the proper version.

But since we are on this topic, maybe we should either make this optional, maybe through the configuration class, or make it not crash.

Even so, in the current version, it will only crash once (the first time).

**Comment by lukasf** [comment]
So the version check thing is solved now.

I hope that I can also do some testing with ffmpeg 4.2 in the next days, then we can bring it into the repo.

**Comment by mcosmin222** [comment]
I have been using it since the test, on my own devices.

Seems fine.

**Comment by lukasf** [comment]
@mcosmin222 On my PC, ARM and ARM64 did not build properly. Some error in "neon" assembly code. Does the same happen on your machine? x86 and x64 work well. Maybe we need to adapt the ffmpeg config to fix this.

**Comment by mcosmin222** [comment]
I actually didn't notice. Yes, ARM and ARM4 didn't build.

**Comment by lukasf** [comment]
I found out the changeset which makes it break, and asked on both the ffmpeg mailing list and the original author of that changeset. Let's see if we can get this fixed.

I think we also need to fix the FFmpegConfig.sh bash script to properly error out if a build error comes. Currently it will just "return 0" at the end, so you only notice errors if you look at the output folders, which is pretty bad.

**Comment by lukasf** [comment]
Oh man, this could be a longer story. First I was in contact with a MS guy who submitted some smaller changes. We found out that the gas-preprocessor script needs to be fixed to compile the code successfully. 

But now that it is fixed, dozens of new build errors pop up. It looks like a whole lot of new ARM/NEON assembly codes have been checked into FFmpeg 4.2, and many of them are obviously not compatible with MSVC armasm compiler. Looks like not many people use that build platform for FFmpeg. It might take a long time for all those errors to be fixed...

**Comment by mcosmin222** [comment]
Well, I guess we shall stay on 4.1.1 for the foreseeable future then.

It might be that the ARM build will be obsolete once the last windows phone drops out of support in 2 months time. Microsoft might focus more on just the ARM64 compiler if the rumors are correct about the ARM64 surface device.

**Comment by lukasf** [comment]
Most of the new code is for ARM64 actually. I don't even know why ARM fails as well, because the affected files have not even changed, which makes it pretty mysterious.

**Comment by mcosmin222** [comment]
well, aside from the AV1 format, we aren't missing much anyway, guess we can just wait till they figure it out.

**Comment by lukasf** [comment]
Ok so all ARM64 build errors go away when using an updated gas-preprocessor from libav instead of the one from FFmpeg. Maybe I will clone this into a separate repo here.

But then there is a bug in armasm (32-bit) from Visual Studio 16.3.x, which makes all ARM builds fail (even FFmpeg 4.1.x cannot build ARM anymore). Now it would already be super helpful to have the new build file from @JunielKatarn where we could specify a different toolkit.

**Comment by JunielKatarn** [comment]
> Ok so all ARM64 build errors go away when using an updated gas-preprocessor from libav instead of the one from FFmpeg. Maybe I will clone this into a separate repo here.
> 
> But then there is a bug in armasm (32-bit) from Visual Studio 16.3.x, which makes all ARM builds fail (even FFmpeg 4.1.x cannot build ARM anymore). Now it would already be super helpful to have the new build file from @JunielKatarn where we could specify a different toolkit.

I’ll finish the script this weekend :)

**Comment by mcosmin222** [comment]
I think they added the custom stuff for their custom snapdragon core.

**Comment by mcosmin222** [comment]
Speaking of ARM64, it appears the project FFmpegInterop doesn't build for ARM64 anyway, due to win2D dependencies.

Can you confirm?

**Comment by lukasf** [comment]
Oh, I was not aware of that. Yes, looks like Win2D is not yet available for ARM64. But a PR has been merged and an official release seems to be pending...

**Comment by mcosmin222** [comment]
This is literally the first time I ever tried to build it for ARM64.

**Comment by lukasf** [comment]
I have opened a PR for FFmpeg 4.2, but I will wait for the new build script to be in place before merging. No need to hurry this one.

**Comment by mcosmin222** [comment]
I wonder if visual studio itself can run on ARM64 🤔

**Comment by MagicAndre1981** [comment]
> I wonder if visual studio itself can run on ARM64

only as x86 emulation, but [it works](https://twitter.com/gus33000/status/1130171201354125313)

![image](https://user-images.githubusercontent.com/8274816/67465342-45754380-f645-11e9-96ef-ac6d946eb9f6.png)

**Comment by lukasf** [comment]
PR merged, closing this.
