### ISSUE TITLE
FrameGrabber is missing

### ISSUE THREAD

**Issue by Satukan** [ffmpeginteropx/FFmpegInteropX#136]
I would like to use the FrameGrabber feature of the library, but the FrameGrabber (and couple of other) objects are missing.
I tried both of downloading the original solution and run locally and download as nuget package:  FFmpegInterop.UWP v1.0.4 (+ the FFmpeg.UWP v4.1.3) and use it in my UWP project. What am I missing?

**Comment by Satukan** [comment]
Thank you, I checked it and I understand the steps, but compiling the FFmpeg library goes a bit too far. I would like to try out the FrameGrabber feature quickly, is there any easy way to to do it, like installing a nuget package or simply downloading and referencing the compiled version?

**Comment by lukasf** [comment]
Ok, if you just want to give this a short try, I can give you x86 ffmpeg binaries:

https://1drv.ms/u/s!Asy3bMoFN_qNh-8O5PZQewHGXtjkww?e=oJXGmz

Extract this to the lib root folder, so you have \FFmpegInteropX\ffmpeg\Build\...

Now open FFmpegInteropX.sln, switch to x86 target and build it. Make sure that the samples work.

To intergrate with your own UWP app, add FFmpegInterop\FFmpegInterop.vcxproj to your own solution ("add existing project") and then add a reference to it from your main app project. Additionally, your app must deploy the ffmpeg dlls to its target folder, so the dlls must be added as Content. See the description at the very end of the readme.md. For simple testing you can also just manually add all ffmpeg dlls to your app project's root folder in VS and set them to Build Action "Content".

For full functionality of this lib, you need a customized ffmpeg build, so arbitrary nuget "ffmpeg UWP" packets cannot be used. So if you want to use this in your project, you will have to setup the build environment correctly for ffmpeg. Once you have everything setup, building ffmpeg (if a new version comes) is merely running a batch file, so from there on, you won't have so much work with it.

**Comment by Satukan** [comment]
Thank you very much, today I could reference it into my project and made it work. Your guideline is straightforward, just need some time to digest it.

The issue is solved and closed at this point.

But I would like to ask how do you deal with the licencing if I plan to use your library in a commercial product? 
- The FFmpeg itself belongs under any licence, it is free to use or I need to contact with them?
- The FFmpegInteropX has (or are you planning to add) any licence in the future?

**Comment by lukasf** [comment]
Glad to hear that you got it running.

Our build script will build FFmpeg with LGPL license, which means that you can use this for free in a commercial project. FFmpegInterop has an Apache style license which is fine with commercial produces as well. We link a few other libs into FFmpeg, all of them can be used in commercial projects.

I am not a legal expert, but the minimum you should do is:
- Have a section in your license agreement or in a separate accessible file which lists all open source libs your project uses
- Include links to each of those libs, so people can theoretically get their sources
- Distribute the license text files from all those libs along with your own binaries

Covering all LGPL requirements 100% is more work. But the above covers the most important aspects and shows your good will. It is a pragmatic approach that many apps follow. The worst you can do is use an open source lib and not include any information about it.

The ffmpeg license file is in the ffmpeg folder (lgpl 3.0), ours is in the root folder, the license files of the other libs appear in the Libs\Build folder after you have built them. I intended to improve the build system to automatically put all license files into one single folder, but it is not there yet.

**Comment by Satukan** [comment]
Thank you, I appreciate, it is a good starting point.
