### ISSUE TITLE
Severe memory leakage on continuous video stream

### ISSUE THREAD

**Issue by susemeee** [ffmpeginteropx/FFmpegInteropX#138]
I am experiencing very high memory usage (over 300MB and growing infinitely) when ffmpeg is fed with continuous raw tcp stream (connected with tcp://)

Due to the stream cannot be seeked, MediaSampleProvider::Flush will never going to be called and it might be causing the issue. Thus, it might be not a 'leakage' causing from some bugs.

If i forcefully call Flush function the memory does not spike, but video does not play correctly, may be related to some internal things about video processing, but I don't know those exactly. (As I know just a little bit about video processing things)

**Comment by mcosmin222** [comment]
The Flush function doesn't usually get called during continuous playback. So it is not critical for keeping memory usage in check. The memory consumption probability happens because incomplete frames are sent over and accumulate in the package queue.

Do you have a way to reproduce this?

**Comment by susemeee** [comment]
So it could be a server issue, what I'm doing is to stream an entire screen using [this source](https://github.com/jean343/RPI-GPU-rdpClient) over the internet.

This behavior could be reproducible if you check out that source and make it as a streamer server.

Note that it uses NVENC but the source has ffmpeg fallback so you don't really need NVIDIA GPU and CUDA stuff.

**Comment by mcosmin222** [comment]
Have you tried a different player, like VLC? it should be able to play that stream.

**Comment by susemeee** [comment]
Using VLC - No. Nothing is being displayed.
Using ffplay - Yes.

**Comment by mcosmin222** [comment]
I'd say the stream is broken.

**Comment by susemeee** [comment]
Checking out if the stream is correct would be a first thing to do then.
