### ISSUE TITLE
Grabbing multiple frames takes too long

### ISSUE THREAD

**Issue by tesar-tech** [ffmpeginteropx/FFmpegInteropX#149]
Hello,
my ultimate goal here is to grab every frame from video file and apply some image processing, compute some values...
Frame grabbing part seems very difficult in UWP. Anyway I managed to grab individual pictures with `FrameGrabber` class:

([Link](https://github.com/tesar-tech/ffmpeg-uwp-test/blob/master/DalsiTest/MainPage.xaml.cs) to full UWP project)
```
var currentFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///Assets/beru.wmv"));
var  stream = await currentFile.OpenAsync(FileAccessMode.Read);
var  frameGrabber = await FrameGrabber.CreateFromStreamAsync(stream);

//...
 int numOfFrames = (int)Math.Floor(mpe.MediaPlayer.PlaybackSession.NaturalDuration.TotalSeconds * 25);
 TimeSpan currentPosition = TimeSpan.Zero;

for (int i = 0; i < numOfFrames; i++)
{
   currentPosition += TimeSpan.FromMilliseconds(1000d / 25d);//every frame (fps is 25 for test video)
  var frame = await frameGrabber.ExtractVideoFrameAsync(currentPosition, true); 
}
```
But it is slow (25 second for 12 sec video). Same task, with saving to file operation takes about 4 seconds with this ffmpeg command: `ffmpeg -i beru.wmv -r 25 $filename%03d.bmp`.

I red some old issues about FrameGrabber, but didn't find what I am doing wrong here.. 

Can I somehow speed up the process with full resolution?

**Comment by lukasf** [comment]
Hi @tesar-tech,

yes, in your scenario, the current FrameGrabber will have very bad performance. The FrameGrabber was made for grabbing one or a few individual frames from specific positions, to create e.g. thumbnail images or seek preview images. It was not designed for grabbing consecutive frames.

Every call to ExtractVideoFrameAsync will involve a seek operation to that position, and a seek will flush all buffers. If you have a video file with frames K1, B1, B2, B3, B4, B5, K2 (where K are key frames, and B are bidirectional frames which depend on previous frames), then to grab B3 the lib will seek to K1, decode K1, B1, B2 and B3, then return B3. If you then grab B4, it will again seek to K1, decode B1, B2, B3, B4 and return that. Obviously that will give you pretty horrible performance.

To grab consecutive frames with good performance, we'd instead need a new API like ExtractNextVideoFrameAsync, which would just grab the next frame from wherever we are right now. That would mean no seek and no duplicate frame decoding. It would also save you from trying to calculate video positions (which might get wrong at some point, and some videos have gaps in timestamps). We could add a Timestamp to the VideoFrame class, so you know where you are right now.

I think it should be pretty easy to add the new API. I will see if I can do a PR in the next days.

**Comment by lukasf** [comment]
Actually, it was so easy that the PR is already there. Please try again with FrameGrabber.ExtractNextVideoFrameAsync() and let me know if you get the performance you expect. 

If you want to squeeze out the maximum performance, you can pass in an IBuffer which will receive the raw pixel data (use width*height*4 as buffer size, format is Bgra8). This avoids any copy operation, the frame is decoded directly into that IBuffer.

If you want to seek in the file, you can use the old ExtractVideoFrameAsync to seek and get the first frame, then call ExtractNextVideoFrameAsync to continue decoding from there.

**Comment by mcosmin222** [comment]
I think using a read-only video filter is faster.

**Comment by lukasf** [comment]
Implementing a native FFmpeg video filter sure would be a way to accomplish what you want. But it would probably be a lot more work, and I don't believe that it will be really any faster. When you use the IBuffer overload, the new method has practically zero overhead. FFmpeg will directly decode into the IBuffer.

The only way how you could really further improve speed is by removing the Bgra color space conversion that currently happens in the FrameGrabber path. Then your code would have to work in the native color space of the video file (which is YUV420P for most codecs). That would be a difficult task I guess.

**Comment by mcosmin222** [comment]
I was thinking more of using winRT video filter in read-only mode. It was implemented to support this kind of scenario.

But as I took another look at this, you are right. The current has virtually no overhead and would probably be faster anyway, since we cannot know for sure what MF does under the hood.

**Comment by lukasf** [comment]
Oh yes, that's one more option. Lots of ways to do this...

**Comment by tesar-tech** [comment]
Thank you for your quick response, useful explanation and immediate "fix". 

Now It is approx 16 times faster and its able to get all (300) frames in 1.5 seconds (with test video 512x288 px and 12 sec duration).

Neat!
