### ISSUE TITLE
How to use it? (NuGet package?)

### ISSUE THREAD

**Issue by tesar-tech** [ffmpeginteropx/FFmpegInteropX#152]
Clearly there is a way how to build and use FFmpegInteropX. It is kind of heavy process. Downloading ffmpeg source, installing tools for building ffmpeg, building it for windows 10 and then referencing project and dlls... And its not one time action. Every developer need to do the same or get copy of built ffmpeg. Also second project in solution seems superfluous to me. 

Is there any official nuget package that solve those issues with one command? Is it possible to create one? 
I found this one: https://www.nuget.org/packages/Hyvart.FFmpegInteropX/ (I believe from @JunielKatarn ) , which works fine, but isn't updated much (actually there is just one version) and there is no connection from this repo (??) or any further information.

**Comment by JunielKatarn** [comment]
> I found this one: https://www.nuget.org/packages/Hyvart.FFmpegInteropX

Hi. I built / published that NuGet from this repository, but I don't intend to maintain it as a general purpose package, but only for audio capabilities of my app [Unjammit](https://github.com/hyvart/Unjammit). That said, I will update once I get ARM and ARM64 to build correctly, but don't plan to keep it up to date.

**Comment by mcosmin222** [comment]
Hi.

You only really need to do the setup for building ffmpeg once. It takes around 30 minutes and involves copy paste commands.

Once you checked out our repository, it will automatically checkout ffmpeg and the other libs and place them where needed.

Then you run a batch script to build. It is as automatic as you can get it. Once you build it, you don't need to do it again until you update the ffmpeg version, which happens once or twice a year.

Maintaining a nuget package is sort of a painful experience, especially as you can combine various versions of the repository with various versions of ffmpeg dlls. It gets nasty over time. I personally have been using this for well over 5 years and found it not that difficult. And importing the project into the solution helps, especially when trying to debug things. Many bugs have been found because I integrated the project in the solution and debugged it under real life circumstances. The project is mature now so that may not sound worthwhile, but I'd personally not give up on the debugging capabilities.

**Comment by tesar-tech** [comment]
Installing nuget package takes few seconds, building everything from scratch at least one hour... **After** that it is much easier as you said. I think - for newcomers - complicated building process is too much to even try... Nuget package would make it much easier, thus make this repo more popular.

**Comment by mcosmin222** [comment]
From my point of view, the issue with nuget is that we need a build machine. Someone either needs to use their local machine, or rent an azure devops VM, which is costly. I am not sure if they offer free support dor open source projects.

**Comment by tesar-tech** [comment]
[They do](https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/). Scroll down to *Azure DevOps for Open Source*. 

That's another thing - I am trying to automate build of my UWP app with azure devops. With nuget package it wouldn't be additional time. With ffmpeginteropX in current state it would be,.. uh...uh..

**Comment by mcosmin222** [comment]
I include the dlls in source control. So it is easy to automate it.

**Comment by lukasf** [comment]
The unclear patent situation was the main reason why I did not distribute any FFmpeg binaries in the past, and I think that was also the reason why Microsoft did not distribute binaries in the original repo. FFmpeg contains countless codecs, many of which are covered under some obscure and intransparent software patents. Distributing binaries might be interpreted as distributing a video decoder.

Installing the build prerequisites is a job of 15-20 minutes (I checked last time I re-installed my dev machine). If that is too much time for someone to get a super powerful library such as FFmpeg into his app, then he is not seriously interested. In the end, I do not really care if the library is used by many people or not. I just want to have some fun working on this project, and I want the lib to work well for me and anyone working with it.

But on the other hand, I also see that having nuget packages would improve many things for us as well (not only for the lazy devs). No more manually referencing any dll files (and fixing projects when file names change). Simplified automatic builds, both of the lib and apps consuming it. We could split the nuget package, so we have one library package "FFmpegInteropX" and one "FFmpegInteropX.FFmpeg" package, with independend versioning. Then you could either include both packages, or you just include the "FFmpegInteropX.FFmpeg" package and reference the lib project directly for debugging. With split packages, we could build the FFmpeg package manually on a local machine, but have an automatic build for the library in the cloud.

Yeah, I am not really decided on this one. Somehow I even like the fact that there are only a few users of the lib - but those who use it are really into it. But then I also see some advantages of the nuget approach. Maybe I could also change my mind on the software patent thing. In the end, I live in Europe where software patents have a much weaker position than in the US. And there are a whole bunch of ffmpeg nuget packages, and also lots of open source players containing ffmpeg, all of which do not seem to have any legal issues.

**Comment by tesar-tech** [comment]
Anyway I managed to create that package (https://www.nuget.org/packages/tesartech.FFmpegInteropX/ ). My intention is to update it from time to time (no automation yet).

**Comment by singhwong** [comment]
> Anyway I managed to create that package (https://www.nuget.org/packages/tesartech.FFmpegInteropX/ ). My intention is to update it from time to time (no automation yet).

hello,
I got an error while using your nuget package.
When I debug uwp in 64-bit, I get the following exception.
`FFmpegInteropLogging.SetLogLevel(LogLevel.Info);//System.BadImageFormatException: 'Not a valid 
 //Win32 application. (Exception from HRESULT: 0x800700C1) '
 FFmpegInteropLogging.SetLogProvider(this);`

**Comment by tesar-tech** [comment]
@singhwong  yes, I also have this error on 64 bit. It is probably caused by dll of wrong version. Will fix that soon. Thnx for reporting.

**Comment by lukasf** [comment]
Official NuGet packages are available now. Closing this.
