### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by mediabuff** [ffmpeginteropx/FFmpegInteropX#154]
I get the above at the first access of FFmpegInteropX in the sample.

FFmpegInterop::FFmpegInteropLogging::SetLogLevel

All necessary dlls seem to be in place - for both cpp and cs samples. Can't seem to figure which file is missing. 

Ran 'procmon' to figure what file is not being loaded. Normally, this tool will reveal. But here I has no clue. 

I believe the factory activation of FFmpegInterop is failing.

**Comment by mcosmin222** [comment]
You need to make sure the dlls match thr build architecture. Eg trying to run an x86 build with ARM dlls.

**Comment by mediabuff** [comment]
Figures. It was postproc.dll
