### ISSUE TITLE
Windows 10 ARM64 build?

### ISSUE THREAD

**Issue by falkor2k15** [ffmpeginteropx/FFmpegInteropX#155]
Is there an ARM64 build/binary available for Windows 10 with the basic ffmpeg engine that I could run from the command prompt and benchmark video encoding on Snapdragon laptops - not to mention the new Surface Pro X? Unfortunately, I lack dev knowledge/experience so would appreciate any support/assistance.

**Comment by mcosmin222** [comment]
You can build ffmpeg for arm64 and run the samples with it. The only thing you need to do is target the c# sample minimum target sdk to 16XXX or newer to build arm64.

**Comment by lukasf** [comment]
@falkor2k15 If I understand you correctly, you are looking for a Windows ARM64 compiled ffmpeg.exe to run benchmarks? What we are developing is a UWP library (dll only) to write Windows Store Apps, and our library supports decoding only.

I did some google search and was surprised that there is not a single Windows ARM64 ffmpeg.exe available anywhere. Our build script only creates UWP library dlls, but I will see if I can somehow make it create a desktop exe file. No promises though.

**Comment by lukasf** [comment]
I think I got it, but I don't have an ARM64 device to test it. 
Please let me know if this works for you:

[ffmpeg_4.2.1_win_arm64.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/4009735/ffmpeg_4.2.1_win_arm64.zip)

It is not a single binary build, but it uses dlls. So you need to put the exe and all dll files into the same folder.

**Comment by lukasf** [comment]
This build should give you better speed:

[ffmpeg_4.2.1_win_arm64_speed.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/4010645/ffmpeg_4.2.1_win_arm64_speed.zip)

**Comment by falkor2k15** [comment]
@lukasf , many thanks - that's exactly what I'm looking for - will test it out and see if it works! I think this could greatly benefit the community as we are missing a native video converter for the Surface Pro X and other ARM64 laptops. Who  knows - perhaps even the Handbrake team could follow suit with this initiative. It's not only needed for benchmarks - but for serious use too. This is, like, my 3rd most wanted ARM64 app behind Google Chrome and Adobe Creative Cloud suite. Can't wait to test it - will report back on the results - cheers.

**Comment by falkor2k15** [comment]
Good news - it's working - I just needed to install Microsoft Visual C++ Redistributable for Visual Studio 2015 (ARM64 version) from here: https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

@lukasf could I please trouble you one last time to recompile it with libx265 (and possibly libx264) to bring it closer to the "static" build of ffmpeg.exe (https://ffmpeg.zeranoe.com/builds/), which clocks in at 62 MB?
https://trac.ffmpeg.org/wiki/Encode/H.265

Normal MP4 is working so there's great potential here!

**Comment by falkor2k15** [comment]
Interesting results so far on the normal MP4 test:
Running the ARM64 version on Snapdragon 850 @ 2.96 GHz was about an 8th quicker compared to running the x64 version on an i5-2400 @ 3.10 GHz.
Running the ARM64 version natively was _at least_ 11 times quicker compared to running the x86 version on the same hardware!

**Comment by lukasf** [comment]
Wow these are some pretty impressive results! Factor 11 speed improvement from emulated x86 to native ARM64, that's a major step. I would have assumed that their emulation is faster than that. Obviously Windows on ARM needs more native applications. It's the typical chicken egg problem...

Unfortunately, it is not a trivial task to compile ffmpeg with additional libraries. It's not like I could just download the lib and include it. First, I'd have to make those libraries compile here manually, with MSVC toolchain, then I'd have to fiddle them into the ffmpeg build. This is probably going to take at least a few hours, if things go well. 

The Zeranone builds include dozens of additional libs, basically every lib that is available gets included. If you really want full featured, regular builds for ARM64, you'd have to ask Zeranone if he can setup Windows ARM64 builds as well. Probably someone would have to donate him an ARM64 Surface to make this happen ;) But who knows. Until now, no none has asked in the Zeranone forums.

I will see if I have some time next year to play with x265/x264. But no promises.

**Comment by mcosmin222** [comment]
I think media playback gets impacted pretty hard due to the memory model of arm vs x86. Arm relies a lot on loading things in their huge caches, whereas x86 can address the memory directly, so the emulation probably tries to achieve the same effect to prevent

**Comment by dganzella** [comment]
I`m trying to run this ffmpeg on an actual ARM64 machine with snapdragon, and Im getting the following error

<img width="293" alt="error2" src="https://user-images.githubusercontent.com/30127664/74262377-815b1400-4cdb-11ea-8b33-3568c34923da.png">

when I try to convert a music or an mp4 file. both speed and normal versions. Does anyone know why?

tried installing Microsoft Visual C++ Redistributable for Visual Studio 2015 (ARM64 version) but no luck.

First it was complaining about a missing AVICAP32.dll and I tried copying from system32 to sysarm32 but then I got the error mentioned previously.

**Comment by dganzella** [comment]
OK I found the issue. I needed to move the DLLS from 

C:\Windows\SoftwareDistribution\Download\684aaa6531057d73fe15dbadbfb6ae49\arm64_Microsoft-Windows-Client-Features-Package~~arm64~~10.0.18362.1\arm64_microsoft-windows-video-for-windows_31bf3856ad364e35_10.0.18362.1_none_648f68e105fa7765

to the same folder as the build to work

**Comment by lukasf** [comment]
@dganzella What OS are you running? Did you uninstall any Windows features? AVICAP32.dll should come with every standard installation. Also "normal" ffmpeg.exe (x86/x64) depends on it.

**Comment by dganzella** [comment]
> 
> 
> @dganzella What OS are you running? Did you uninstall any Windows features? AVICAP32.dll should come with every standard installation. Also "normal" ffmpeg.exe (x86/x64) depends on it.

windows 10 for ARM.

<img width="359" alt="Untitled" src="https://user-images.githubusercontent.com/30127664/74264006-b026b980-4cde-11ea-9bb3-3d1e69cf5096.png">

I was able to do it, I needed the ARM version of the AVICAP32.dll, and also others. Which are available here:

 https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

Weirdly enough, the ARM version is being slower than emulated x86 vesion for me.

**Comment by lukasf** [comment]
So installing vc_redist.arm64.exe solved the problems?

@falkor2k15 reported 11x speed increase. Maybe the x86 version used HW acceleration? My build only has very few external libs, so it might be that HW acceleration is not working for you. If you want to do performance comparisons, you need to make sure you compare the exact same encoder or decoder. It could also be that the x86 version has an optimized external codec while my build only has a slower internal codec.

**Comment by lukasf** [comment]
I am working on setting up a build environment that builds FFmpeg for all platforms with exact same ffmpeg version and exact same libs included. Only that will allow real performance comparisons. I already managed to include x264, and I hope I will be able to include x265 and VP9 as well.

Here is a first ARM64 build that contains x264:

https://1drv.ms/u/s!Asy3bMoFN_qNiIo9DAmY6eM7YCG7Wg?e=EznOHs

This is also a static version (1 exe file, no dlls).

**Comment by dganzella** [comment]
> 
> 
> So installing vc_redist.arm64.exe solved the problems?
> 
> @falkor2k15 reported 11x speed increase. Maybe the x86 version used HW acceleration? My build only has very few external libs, so it might be that HW acceleration is not working for you. If you want to do performance comparisons, you need to make sure you compare the exact same encoder or decoder. It could also be that the x86 version has an optimized external codec while my build only has a slower internal codec.

Installing it solves the issue BUT i had to move the installed DLLs to the very same folder as the build you made. Just installing it didnt solve the problem, or maybe it only didnt because I first copied the wrong version of the DLL in the sysarm32 (its like system32 but for arm) folder, which made it registered somewhere in my system wrongly

So it now only works with the DLL in the same folder, since im guessing it takes priority

Here are my tests:

These are the results of converting a 70 MB Mp4 to AVI

  Stream #0:0 -> #0:0 (h264 (native) -> mpeg4 (native))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))



X86

1)
bench: utime=1114.656s stime=5.688s rtime=327.506s
bench: maxrss=166012kB

ARM

1)
bench: utime=1674.688s stime=5.250s rtime=439.510s
bench: maxrss=146520kB

**Comment by dganzella** [comment]
> 
> 
> I am working on setting up a build environment that builds FFmpeg for all platforms with exact same ffmpeg version and exact same libs included. Only that will allow real performance comparisons. I already managed to include x264, and I hope I will be able to include x265 and VP9 as well.
> 
> Here is a first ARM64 build that contains x264:
> 
> https://1drv.ms/u/s!Asy3bMoFN_qNiIo9DAmY6eM7YCG7Wg?e=EznOHs
> 
> This is also a static version (1 exe file, no dlls).

You are correct. I do need to test the same very versions.

I was comparing Zeranoe with yours.

Anyway my main object was to see if I could open the ARM64 DLL from the x86 ffmpeg EXE.

My final objective was to use the X86 handbrake UI and load the FFMPEG ARM64 to improve the performance without needing to remake the handbrake entirely.

But it seems to be impossible. An emulated x86 EXE cannot load ARM64 DLLS.

**Comment by dganzella** [comment]
It seems I will need to wait until November 29 2020 to be able to recompile the hanbrake UI for ARM64

https://github.com/dotnet/wpf/milestone/5

**Comment by dganzella** [comment]
> 
> 
> I am working on setting up a build environment that builds FFmpeg for all platforms with exact same ffmpeg version and exact same libs included. Only that will allow real performance comparisons. I already managed to include x264, and I hope I will be able to include x265 and VP9 as well.
> 
> Here is a first ARM64 build that contains x264:
> 
> https://1drv.ms/u/s!Asy3bMoFN_qNiIo9DAmY6eM7YCG7Wg?e=EznOHs
> 
> This is also a static version (1 exe file, no dlls).

this is with the static version:

bench: utime=1487.469s stime=4.969s rtime=343.227s
bench: maxrss=147056kB

**Comment by lukasf** [comment]
I finally managed to build FFmpeg Win32 with x264 x265 and libvpx. x265 was the worst of all. Lots of trouble to get it actually compiling at all, then lots of extra trouble and hacks required to get it compiling also for ARM64. That was hell of a work. I don't even know why I am doing this :) There are many open issues for ARM(64) build issues on the x265 tracker, so it's not only me having those problems. Looks like they do not really care about that platform right now (unlike x264 and libvpx).

For performance comparisons, it's best to use x264 or VP9, because both are compiled with lots of ARM NEON assembly optimizations. They will show you how properly optimized ARM64 code compares to emulated x86 code, while x265 is without any ARM assembly code.

Here you can download the builds for x86, x64 and ARM64:

https://1drv.ms/u/s!Asy3bMoFN_qNiIpCVQ62LoDFjMHI5g?e=8heVB6

**Comment by dganzella** [comment]
@lukasf WOW. where is the code? did you create a branch of this project?

**Comment by lukasf** [comment]
Yes I have it on a branch "build-script". But it is not yet all checked in. And also, it currently requires manual patches to x265 and also one change to ffmpeg sources (for x264, because ffmpeg hard codes x264 to be dll imported while I want it statically linked).

**Comment by xingyun86** [comment]
> This build should give you better speed:
> 
> [ffmpeg_4.2.1_win_arm64_speed.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/4010645/ffmpeg_4.2.1_win_arm64_speed.zip)

Can you tell me how to build it? I need modify some codes and rebuild. I also need lib files.Thanks very much.

**Comment by mcosmin222** [comment]
Our build script should handle that.
