### ISSUE TITLE
mp4 video does'nt play

### ISSUE THREAD

**Issue by mediabuff** [ffmpeginteropx/FFmpegInteropX#157]
This simple streaming .mp4 does'nt paly

http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

**Comment by lukasf** [comment]
A few people already reported streaming problems. I did not really have time to investigate yet. Most devs here are focused on local file playback, so streaming did not have much priority. Still, I'd like to get streaming working. I hope that I will have some time next year to look into this.

**Comment by lukasf** [comment]
I have a PR ready which fixes most streaming issues. There was a bug where the stream URI conversion was broken, which is why streams did not work anymore. You can already try the solution in the "fix-streaming" branch.

**Comment by lukasf** [comment]
The fix is available on master branch now. Closing this.
