### ISSUE TITLE
Not working yet

### ISSUE THREAD

**Issue by mediabuff** [ffmpeginteropx/FFmpegInteropX#159]
[mp4.txt](https://github.com/ffmpeginteropx/FFmpegInteropX/files/4023424/mp4.txt)
The fix is available on master branch now. Closing this.

_Originally posted by @lukasf in https://github.com/ffmpeginteropx/FFmpegInteropX/issues/157#issuecomment-570808327_

Log

**Comment by lukasf** [comment]
I have just tested again on master branch and the stream plays well in both CPP and C# sample app. Please make sure you pulled the latest changes and don't have any local checkouts. Then run one of the sample apps, paste the URI and hit return.

**Comment by lukasf** [comment]
Were you able to re-test this? I could not see any issues with the mp4 stream you posted.

**Comment by mediabuff** [comment]
Yes, this works. Closing the issue. Thanks for your support.
