### ISSUE TITLE
Stream switching is slow for DASH streams

### ISSUE THREAD

**Issue by lukasf** [ffmpeginteropx/FFmpegInteropX#165]
When playing DASH streams, I noticed that switching of video streams is very slow. Some investigation showed this call pattern on our MSS after selecting a new stream:

1. OnStarted with current position
2. OnSwitchStreamRequested with new stream
3. OnStarted with current position (again)

So switching of streams causes two seeks, which in total takes about 6 seconds for my DASH streams. I don't know if it would be possible to get 100% seamless switching, but the situation could probably be improved by removing at least one of the two seeks.

I imagine us having a SelectVideoStreamAsync method on the MSS instance. The MSS will internally trigger the stream selection and discard at least one of the following seek operations.

**Comment by mcosmin222** [comment]
The first seek on the initial stream seems redundant.

But how exactly would the mss trigger the stream selection internally? I thought we can only respond to a change request, not trigger it ourselves.

Can't we check if the seek position is the same as the current position? I guess this would imply keeping track of the playback position but that shouldn't be an issue.

**Comment by lukasf** [comment]
We can access the PlaybackItem, and through that we can change the video stream. When using BufferTime > 0, the seek position will not be our current decode position, decode position could be multiple seconds ahead of playback. That also means that if we switch streams without any seek, there would probably be some seconds without video, until the video reaches the decode position where the new selected stream kicks in. So having at least one seek kind of makes sense, when using BufferTime > 0.

I would not try to guess positions from sample rendered event. This could prevent fine-grained seeking operations because they are accidentially interpreted as belonging to a stream switch. I'd rather handle the switching internally and then prevent the seek when we know it will come. As an optimization, we could use the sample rendered time to verify that the seek corresponds to our stream switching, so if the seek is way off, we do not prevent it.

**Comment by mcosmin222** [comment]
Well, I guess we can give it a try, see how it works out.

**Comment by mediabuff** [comment]
Please add an additional issue of initial lag - or first frame - 21 secs

**Comment by mcosmin222** [comment]
So i think we first need to expose better stream info and then do this. I might have some time this week for some twinkling.

**Comment by lukasf** [comment]
Initial lag will not be addressed here. We'd have to submit patches to FFmpeg to improve the situation. That could be a long story.

I already have something running here for stream switching. I observed MF errors when switching takes place too fast, so I had to implement some additional locking plus delays, to make sure this runs well. I will create a PR soon, then you can take a look at it.

**Comment by mcosmin222** [comment]
The MF errors are probably worth reporting to Microsoft. They really need to ger their act together and fix the bugs!

**Comment by lukasf** [comment]
Closing this one. We do already skip the first seek on stream switch. If we omit the second seek as well, we will have a gap in playback that is definitely longer than the actual seek, so that makes no sense. I just re-tested that with the current implementation. When using the new stream buffer, the gap gets even larger, the more buffer we use. So we definitely need that second seek, no way to avoid it. This is as good as we can do when using ffmpeg for stream parsing.

True seamless seeking would require a totally different architecture with custom stream parsing, and that is probably not going to happen, at least not by me.
