### ISSUE TITLE
Unable to play 'mpegts' stream 

### ISSUE THREAD

**Issue by mediabuff** [ffmpeginteropx/FFmpegInteropX#167]
Eg stream from local streaming box: http://192.168.86.56:5004/auto/v4.1

Get failure as follows:
`[tcp @ 0B8A8040] Connection to tcp://192.168.86.56:5004 failed: Error number -138 occurred
Exception thrown at 0x769C1EB2 (KernelBase.dll) in MediaPlayerCPP.exe: WinRT originate error - 0x80004005 : 'Failed to open media.'.
Exception thrown at 0x769C1EB2 in MediaPlayerCPP.exe: Microsoft C++ exception: Platform::Exception ^ at memory location 0x017CE27C. HRESULT:0x80004005 Unspecified error
WinRT information: Failed to open media.
Exception thrown at 0x769C1EB2 in MediaPlayerCPP.exe: Microsoft C++ exception: Platform::Exception ^ at memory location 0x017CDFE0. HRESULT:0x80004005 Unspecified error
WinRT information: Failed to open media.
Exception thrown at 0x769C1EB2 (KernelBase.dll) in MediaPlayerCPP.exe: WinRT originate error - 0x80004005 : 'Unspecified error'.
Exception thrown at 0x769C1EB2 in MediaPla`

1) ffplay - plays it

 `Input #0, mpegts, from 'http://192.168.86.56:5004/auto/v4.1': f=0/0
  Duration: N/A, start: 57739.434089, bitrate: N/A
  Program 3
    Stream #0:0[0x31]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 1920x1080 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x34](eng): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, 5.1(side), fltp, 384 kb/s
    Stream #0:2[0x35](spa): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, stereo, fltp, 192 kb/s`

2) vlc plays
![live stream](https://user-images.githubusercontent.com/5080114/72684082-75e54600-3aab-11ea-9639-28777b02055c.PNG)

**Comment by mediabuff** [comment]
I am able to use VLC. So, this is a not work issue.

**Comment by lukasf** [comment]
It's strange that we get such a low level error then.

Anyways, I can only further intestigate this, if you can show me a way to reproduce this. I don't have streaming devices at hand, so I wouldn't know how to simulate this issue. And I guess you can't open ports on your firewall, so the device can be accessed through the web?

**Comment by mcosmin222** [comment]
Does the UWP version of VLC play the stream? There are slight differences in API behaviour between the UWP and the classical desktop versions of VLC.

**Comment by lukasf** [comment]
You could also try to do a http get on the Uri from your app using HttpClient. This will show you if the app can connect to that address and port. Also check the response. Maybe you get a broken redirect or soemthing like that.

**Comment by mediabuff** [comment]
Question, why would ffplay but not ffmpeginteropx ?

**Comment by mcosmin222** [comment]
Ffplay is not running in a sandbox.

**Comment by mediabuff** [comment]
Thank you all. Enabled 'private network' capability in the manifest of MediaPlayerCPP/MediaPlayerCS
