### ISSUE TITLE
Build Fails due to XML2 error

### ISSUE THREAD

**Issue by payyavula** [ffmpeginteropx/FFmpegInteropX#174]
BuildFFmpeg_VS2017.bat scr fails with ERROR: libxml-2.0 not found using pkg-config

I see libxml2 in folder where bzip2,zlib and libiconv are. 

Reverting back to older version as on  Tuesday, January 14, 2020 9:48:10 PM works fine.

@lukasf , looks like your recent check-in is causing the build error. could you please take a look at it?

**Comment by lukasf** [comment]
Hi @payyavula 

you need to use the new PowerShell build file. Please check this link for details:

https://github.com/ffmpeginteropx/FFmpegInteropX/issues/153#issuecomment-569509912

I will remove the old build file or make it call the new PS script.

**Comment by lukasf** [comment]
Closing this. Feel free to re-open or create a new issue if you need support.
