### ISSUE TITLE
Unable to play av01 encoded video

### ISSUE THREAD

**Issue by sudongg** [ffmpeginteropx/FFmpegInteropX#175]
Hi, @lukasf 
I use IDM to download YouTube Videos. Some videos can only play audio.
Use potplayer to view the video encoded as AV01.

Below is the video sample link:
https://www.dropbox.com/s/vq27zgi08p996un/Shawn%20Mendes%2C%20Camila%20Cabello%20-%20Se%C3%B1orita.zip?dl=0

**Comment by mcosmin222** [comment]
Do you have the latest ffmpeg build?

**Comment by sudongg** [comment]
@mcosmin222 
use ffmpeg 4.1 2, FFmpegInteropX use the August 2019 version. I have been waiting for the project to be updated after FFmpegInteropX supports DASH.
Please try to play the sample provided by me with the latest version, if it can play normally, I will upgrade the latest version.
Thank you.

**Comment by lukasf** [comment]
AV1 is only supported in ffmpeg 4.2 and Higher.

**Comment by sudongg** [comment]
@lukasf Thank you. I use the latest version FFmpegInteropX + ffmpeg 4.2.2 can play normally.
