### ISSUE TITLE
Important: Switch to NuGet packets

### ISSUE THREAD

**Issue by lukasf** [ffmpeginteropx/FFmpegInteropX#177]
I will be moving FFmpegInteropX to Nuget!

There will be two Nuget packets:

- FFmpegInteropX
  - The library itself
  - Has a dependency to FFmpegInteropX.FFmpegUWP (4.0.0 or higher)

- FFmpegInteropX.FFmpegUWP
  - The FFmpeg build for UWP platform
  - Includes dll files, libs, includes and license files
  - Two purposes:
    - Provide runtime dependencies (dlls) for apps
    - Provide build dependencies for our library

Both packets are already available as prerelease versions on nuget already. If you want to try them, please don't forget to remove the FFmpeg dlls referenced in your app project, to prevent build errors.

The changes are done in PR #173 

Benefits:

- App devs won't have to build FFmpeg itself
- If they do not want to debug, they don't even need the lib project
- No more need to manually deploy FFmpeg dll files in app projects!
- The library project itself has a build reference to FFmpegInteropX.FFmpegUWP. This packet has everything that is needed to build our library. So even library devs don't need to build FFmpeg, and they don't need to manually handle all those files.
- Flexibility: Both packets can be updated independently
- If app devs want to debug into our lib, they can remove FFmpegInteropX from their app, add only FFmpegInteropX.FFmpegUWP instead, and include our library project into their app solution. This setup is also used in the sample apps. It is similar to what we had before, just that you don't need to manually build, reference and deploy FFmpeg dlls.
- If app devs want to use their own FFmpeg build, they can include our library project into their app solution, and add their own FFmpeg dlls instead of using FFmpegInteropX.FFmpegUWP. The library just needs FFmpegInteropX.FFmpegUWP for building. At runtime, other FFmpeg dlls can be used.
- The license files for all libs contained in the FFmpeg build are included in the FFmpegInteropX.FFmpegUWP packet, to make it easier to comply with licenses.

Versioning:

FFmpegInteropX starts at 0.9.0. My plan is to make a 1.0.0 release at some point with breaking changes (remove all those old deprecated APIs, maybe also change namespace to FFmpegInteropX).

FFmpegInteropX.FFmpegUWP will use the FFmpeg version number, but the third number is multiplied with 100. This gives me two last digits to increment, just in case I need to fixup stuff and recompile. So the first release of FFmpeg 4.2.2 will be 4.2.200, and if I need to rebuild it, it will be 4.2.201, 4.2.202,...

Repository structure:

I think later it would make sense to also split the repo. So this library repo would only contain the library itself and samples. A new second repo would be added for the FFmpeg build system. The benefit is that normal library devs don't need to checkout all those FFmpeg library subrepositories, saving some disk space, and it would also cleanup and simplify the file structure.

**Comment by TaoziDB** [comment]
Is it possible to have a nuget version for both package for  Windows 10 SDK 10.0.14393?

**Comment by lukasf** [comment]
You should be able to just use the standard package, even if your app has a lower target version. The C# sample app for example is still configured as 10.0.17763.0, but it runs perfectly well with packets targeting 10.0.18362.0.

**Comment by mcosmin222** [comment]
Sounds good to have the ffmpeg dlls separated from the rest of the library.

I am guessing you will use azure open source build services to generate the packages?

**Comment by lukasf** [comment]
Thanks to nuget, building our lib is now pretty trivial. It would make sense to use some kind of automation. Not sure what is best there. Azure Pipelines is sure an option. GitHub also has some support for automatic builds. I have not really investigated these, it is a second step once the NuGet stuff is in place.

**Comment by lukasf** [comment]
It was pretty easy to extend the existing AppVeyor task to build a nuget packet and add it to artifacts. This makes is possible to download nuget packets for every PR and every change of a branch. AppVeyor will even automatically host a custom nuget packet feed. So you can add it in VS and select any build from AppVeyor CI through normal VS nuget GUI.

**Comment by lukasf** [comment]
This is finally done! NuGet packets are available now. Let's see how we work with this. I will leave this issue open for a while, in case there are discussions.
