### ISSUE TITLE
Remove blank space

### ISSUE THREAD

**Issue by pashmak73** [ffmpeginteropx/FFmpegInteropX#178]
Hi,
Is it possible to remove blank/black space of an video?
I know mediaelement has an option for that but I want to see if there is something exists for that or not? 
(I'm want to use it in to Transcode videos)
Something like that is exists in Photos app>
![image](https://user-images.githubusercontent.com/46992431/78499085-ccd1f180-7763-11ea-8efc-de3746285bef.png)

**Comment by mcosmin222** [comment]
It is technically possible to do that via video effects. 

What you see in the screenshot is probably something done with the size of the media player element itself rather than an effect in the video stream. They simply size the media player element to a multiplier of the video aspect ratio.

**Comment by pashmak73** [comment]
Thanks for quick answer.
Is it possible to do something like this using win2d? create mss with ffmpeginteropx and use win2d for videoscale and transcode it via MediaTranscoder.

**Comment by mcosmin222** [comment]
You can take a look at the list here: 

https://microsoft.github.io/Win2D/html/N_Microsoft_Graphics_Canvas_Effects.htm

I am not sure if win2D has such an effect. There might be built-in effects for transcoding within the winRT framework but I don't remember where to find them.

**Comment by lukasf** [comment]
I think this will be difficult to achieve. You don't know where the black bars are, until you have decoded at least parts of the video. But you need to know it before starting the transcode, because it changes your output resolution. So you'd need a two pass system, where you first decode into the file, try to find the black areas in a reliable way, then close it, then start transcoding using this information to crop the image.

**Comment by pashmak73** [comment]
Thanks for replies.
@lukasf 
I know where exactly are black bars. it was too much easy with using [VideoTransformEffectDefinition ](https://docs.microsoft.com/en-us/uwp/api/windows.media.effects.videotransformeffectdefinition) class.
Source>
![12 mp4_20200405_174338 799](https://user-images.githubusercontent.com/46992431/78509008-33750080-77a0-11ea-8e70-77c8ba037c3a.jpg)
Output>
![RMTJOKAR1373_VID_20200504_33402546 mp4_20200406_005053 655](https://user-images.githubusercontent.com/46992431/78509019-438ce000-77a0-11ea-945a-50410ba1bc69.jpg)

It's converted to my desire size and removed black bars by scaling the frame (i choose where to cut).

Thanks a lot guys.
