### ISSUE TITLE
Is H265 hardware acceleration a supported configuration on HoloLens-2 using FFmpeg?

### ISSUE THREAD

**Issue by payyavula** [ffmpeginteropx/FFmpegInteropX#182]
Before I debug further, I would like to check if H265 hardware acceleration is a supported configuration on HoloLens-2 using FFmpeg?

My Unity running on HL2 using FFmpeg 4.2 and FfmpegInteropX etc, works fine for H264 with hardware acceleration. However, FFmpeg crashes for the H265 RTP video stream.

**Comment by lukasf** [comment]
I don't own a HoloLens-2, and I could not find official specs on it's HW decoding capabilities. HoloLens-1 only supports H264, but HoloLens-2 has a SnapDragon 850, which should be able to decode H265/HEVC (at least it does so on smartphones).

What FFmpeg version are you using really? 2.3 is extremely old and I don't believe it even works with FFmpegInteropX. FFmpegInteropX requires a 4.x version of FFmpeg for proper playback and FFmpeg 4.2 is required for software decoding of H265. So if you cannot HW decode HEVC and you have FFmpeg 4.1 or lower, then you cannot play H265 at all. You will receive an exception with E_FAIL in that case. Please note that the CPP sample does not have proper error handling, so it might crash in that case. The C# sample should catch those errors and show a proper message box.

Oh and to HW decode H265/HEVC, you need an extension installed. Call `CodecChecker.CheckIsHEVCVideoExtensionInstalledAsync()`, if it returns `false`, call `CodecChecker.OpenHEVCVideoExtensionStoreEntryAsync()`. For x64 there is a free extension, but on other platforms there is only a paid one for about 1$/1€.

**Comment by anandx** [comment]
@payyavula are you able to share your code for hardware accelerated HoloLens 2 H264 playback?

**Comment by payyavula** [comment]
Thanks @lukasf for your feedback. let me try with CheckIsHEVCVideoExtensionInstalledAsync.
I corrected FFmpeg version to 4.2

**Comment by payyavula** [comment]
@anandx , To enable hardware acceleration in FFmpeg, I followed https://trac.ffmpeg.org/wiki/HWAccelIntro
and then followed steps as in https://github.com/ffmpeginteropx/FFmpegInteropX.
then used these libraries to compile and test sample app MediaPlayerCPP

**Comment by lukasf** [comment]
@payyavula The HW acceleration in FFmpegInteropX is handled by UWP, not by FFmpeg, so you do not need to follow that guide on the FFmpeg wiki. Can you try to run the C# sample instead of CPP? First, it does not crash if a file or stream cannot be played. Second, it handles CodecChecker.CodecRequired event, so it should open the Windows Store page of an extension if it is needed.

**Comment by lukasf** [comment]
Closing this. Feel free to re-open or create a new issue if you need support.

**Comment by payyavula** [comment]
Thanks @lukasf  I could make the H265 decoder run on HoloLens-2 with hardware acceleration and decoding happening on GPU.

**Comment by lukasf** [comment]
@payyavula Glad to hear that it is working. Thanks for the followup.

**Comment by RookieDeveloper-Wang** [comment]
@payyavula 
Hello, can you share the effect of using unity, ffmpeg, ffmpegInteropX on hololens 2 and how to implement it?
I am very interested in it and I want to try it~
Thank you~~
