### ISSUE TITLE
Encode

### ISSUE THREAD

**Issue by pashmak73** [ffmpeginteropx/FFmpegInteropX#183]
Hi,
Do you guys have any plans to add encode part of ffmpeg as well?
Thanks in advance.

**Comment by mcosmin222** [comment]
I don't think there is anything inheritely difficult that prevents us from doing that, other than maybe licensing and the amount of time we have for that. I think neither of us have too much time for it.

**Comment by lukasf** [comment]
Much like @mcosmin222 said, my free time is also pretty limited lately, plus I do not have a use case for that functionality. So I do not see myself adding this anytime soon. But generally I would be open to include this, in case anyone wants to do work, and I would try to help with it as far as possible. I think it would be quite a bit of work to get this running correctly.

**Comment by mcosmin222** [comment]
You should be able to use this project to encode, at least partially. The encoding part requires 2 components, a sample source, and the actual encoder itself. You can use this project as the sample source as you would normally use a media stream source (not the playback item itself) for decoding, and a winRT built-in component for encoding as the 2nd part. I think for video, winRT supports most formats for encoding. For audio it is a bit trickier though.

**Comment by pashmak73** [comment]
Thanks for your answers, I wasn't around for a couple weeks so sorry for the delay.
@mcosmin222 
I'm planning to create a broadcasting app which works with rtmp protocol, something like obs studio or https://yellowduck.tv/ , so as I research about WinRT, WinRT can't help itself because there is no profile for transcoding to FLV stream/file.

I found a project provided by MS which will allows you to broadcast with stsp protocol
https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/SimpleCommunication

But I don't know how to edit to support rtmp.

**Comment by lukasf** [comment]
Can we close this for now? It does not look like anyone is currently up for the job of adding encoding to the lib.
