### ISSUE TITLE
"The parameter is incorrect" Error creating mediaplaybackitem. FFMpegMSS.CreateMediaPlaybackItem();

### ISSUE THREAD

**Issue by villagra** [ffmpeginteropx/FFmpegInteropX#185]
Hi Chiefs,
I'm having troubles with a couple local video files.
The first one throws a ArgumentException "The parameter is incorrect" when creating the MediaPlaybackItem:

_playbackItem = FFMpegMSS.CreateMediaPlaybackItem();

And the other one can't reproduce the audio, doesn't report a video duration and stops playing after some seconds. Maybe this video file is not fully correct, not sure, but I tried with vlc and both can be reproduced.

Here are the files to test:
https://1drv.ms/u/s!Ajg8AuGl0XTgqL4-t5aRUIJOokyw9w?e=BM0CnC

I tried with both my app and the FFmpegInteropX sample app (latest bits available)

(Let me know when you download them to take them down)

Thanks.

**Comment by mcosmin222** [comment]
Hi

Downloading that large 4.3GB file is giving me some troubles.
is there any way you can trim it down a little? I realize that editing it might fix the file, so it's a longshot, but let's see if that works.

I will let it download again over night, maybe this time will work.

**Comment by villagra** [comment]
yeah, i didn't want to modify the file and risk to fix it... let me know if you still troubles and i can try to upload it somewhere else. thanks

**Comment by mcosmin222** [comment]
hmm I did manage to download it this time around.
I will check to see what's up.

**Comment by mcosmin222** [comment]
So the argument exception is caused by a video chapter having the start time negative.
I guess this is a bug in our framework.
I will fix it ASAP.

**Comment by mcosmin222** [comment]
Check branch origin/issue-185, it should fix the argument exception

As for the no duration, I will handle it later.

**Comment by villagra** [comment]
@mcosmin222 I just tried that branch and the fix works. Thanks!
And about the other file yep, it must be pretty broken, only VLC can play it correctly.
