### ISSUE TITLE
SetVideoEffects not working

### ISSUE THREAD

**Issue by 07101994** [ffmpeginteropx/FFmpegInteropX#188]
Hi, Thanks for creating/maintaining this project.

I am using the below code to add video effects.
`FFmpegMSS.SetVideoEffects(new AvEffectDefinition[] { new AvEffectDefinition("rotate", "45*PI/180") });`

But it seems it doesn't have any effect on the video. `SetAudioEffects` is working fine.

Let me know if you need further more details.

Is there anything I'm missing?

**Comment by lukasf** [comment]
Hi @07101994, you are right, the API does not work. We intended to implement it, but there were some problems with it and it was never done. Maybe we should remove the API until someone does an actual implementation.

**Comment by mcosmin222** [comment]
The problem with implementing it is that we lose hardware acceleration, and while it is ok for audio, for video it is quite the performance hit.

**Comment by 07101994** [comment]
Hi @lukasf & @mcosmin222, Thanks for the details.

Is there any way through which I can use the crop video filter in FFmpeg?

Any workaround through UWP APIs will also work.

**Comment by lukasf** [comment]
There does not seem to be a UWP API to realize that. There is one that works for transcoding, but not for media playback.

It would be possible to do this in Win2D, like we did with our BasicVideoEffect. One downside is that you only have one effect instance per MediaPlayer. If you play multiple files with MediaPlaybackList, you would get problems synchronizing the effect to the currently playing file. If you don't use MediaPlaybackList, then I think this could work well.

One other idea would be to use MF_MT_MINIMUM_DISPLAY_APERTURE to set the crop rectangle per file on MediaFoundation layer. We already do this for some video files, check UncompressedVideoSampleProvider::CreateStreamDescriptor(). You'd have to kind of hack this into the lib, and I think then you cannot change it during playback (at least not on older Windows versions, the most recent ones are supposed to support this, as I heard). This might be the best way performance wise, and it works cleanly per-file.

**Comment by lukasf** [comment]
Hi @07101994, I just noticed this API: Check MediaPlayer.PlaybackSession.NormalizedSourceRect. It allows you to define a subsection of the actual video to be rendered. Crop/Pan/Zoom should all be possible with this, according to docs. No messing with our lib or FFmpeg required.

**Comment by mcosmin222** [comment]
Once #203 is merged, we will be one step closer to having these filters work.
It will also depend on ffmpeg to implement hw support for video filters.

**Comment by lukasf** [comment]
Afaik, there is no hw support for filters in ffmpeg yet, so filters would still only work in sw mode.

**Comment by mcosmin222** [comment]
For directx 11, not yet. But there is work being done there.

We can now also use pixel or compute shaders for filtering.

**Comment by mcosmin222** [comment]
Support has been implemented.
