### ISSUE TITLE
System.Exception: Unspecified error (Exception from HRESULT: 0x80004005)

### ISSUE THREAD

**Issue by 07101994** [ffmpeginteropx/FFmpegInteropX#190]
I'm receiving `System.Exception: Unspecified error (Exception from HRESULT: 0x80004005)` error on a few Windows 10 devices while calling `FFmpegInteropMSS.CreateFromStreamAsync(readStream, Config);` method of FFmpegInterop. Here readStream is a stream of local file.

Devices on which I'm receiving this error:
- HP 246 G6 Notebook PC
- PC-VN770VG6B
- 10B60008US

Windows Version:
- 10.0.18363

On a few devices, it is working fine. Not sure what I'm missing.

Can anyone help me with this?

**Comment by mcosmin222** [comment]
Hi.

We will need a file for this to reproduce.

You have to keep in mind that some files are broken and will generate errors we haven't thought of. You will never have a 100% clean player

**Comment by 07101994** [comment]
Hi @mcosmin222, thanks for the reply.

Do you mean that these errors are related to the different video files?

**Comment by mcosmin222** [comment]
It is best to wrap the Create method calls in a try-catch and simply move on to ignore broken files. There are many things that can go wrong when creating the stream source. Unless you have a specific file to showcase the errors, we don't really have anything to do and it...

**Comment by 07101994** [comment]
Hi @mcosmin222, Is there any way through which I can play below file extensions with the FFmpeg interop library?

- VIDEO_TS.BUP
- VIDEO_TS.IFO
- .part

I'm facing `System.Exception: Unspecified error (Exception from HRESULT: 0x80004005)` error while trying to open the above file extensions.

Thanks for your help.

**Comment by mcosmin222** [comment]
These look like DVD files. At the moment, no.

**Comment by lukasf** [comment]
.part files are usually partially downloaded files. Some of these might play, some not. Usually, such files can only be played, when at least the beginning and ending of the file has been completely downloaded. But even then, it depends on the actual format. We cannot guarantee anything about partially downloaded files.

**Comment by 07101994** [comment]
@mcosmin222 & @lukasf - Thanks for the details.
