### ISSUE TITLE
Video frame server performance 

### ISSUE THREAD

**Issue by mcosmin222** [ffmpeginteropx/FFmpegInteropX#198]
Hello @lukasf,

I have been playing around with the video frame server mode in MediaPlayer.
It looks pretty interesting and allows quite a few fancy things, including video effects (yes, i gave up on the official version).

I've been worried about excessive audio processing causing desync between audio and video. So you have any experience about it?

Thanks.

**Comment by mcosmin222** [comment]
It is a back and forth really. I added a task delay in the frame processing event and it seems to induce frame drops. So it's not really that nice for audio & video together, but should work for ads lol.

**Comment by lukasf** [comment]
Did you try using MediaPlayer.GetSurface() instead of doing custom rendering? The surface can be used with Composition and will update automatically. Then it should be possible to apply composition API effects.
