### ISSUE TITLE
What if we did the pass through ourselves? 

### ISSUE THREAD

**Issue by mcosmin222** [ffmpeginteropx/FFmpegInteropX#199]
So I was thinking the other day about hardware acceleration in decoding (for both audio and video), and related other functionality (ffmpeg audio and video transcoding, encoding, DASH, gapless playback etc).

I realized that we should be able to do the operations that the media pipeline does to enable pass through on our own, without relaying on winRT, which might have buggy or incomplete abstractions. I found that we can enumerate existing transforms and also create instances of it, and we should be able to create the entire pass through pipeline ourselves. 

This should allow us to pass our demuxed sample buffers down the line and get the raw data back in our application before sending it out to the media stream source.

I realize this is quite the effort to make, so I will silently do some research on this in the background (this is after all a nice to have thing, but not really a must-have).

What do you think @lukasf?

**Comment by mcosmin222** [comment]
So it seems directx provides all the necessary things to do the decompression in hardware. Now the biggest issue seems to be matching the GUIDs of media foundation with those of DirectX
Yoh would think that 2 media technologies created by the same company would use matching GUIDs for that, but seems I expect too much.

**Comment by lukasf** [comment]
It's quite some work, but it would definitely be possible, and it would solve a bunch of issues. So if you can get this working, it would be a great addition!

Not exactly sure which GUIDs you mean.

I guess you know this guide:

https://docs.microsoft.com/en-us/windows/win32/medfound/supporting-direct3d-11-video-decoding-in-media-foundation

It shows the basic workflow of decoding frames using D3D11. You can also check d3d11va decoders in vlc, lavcodec and others, for reference.

Be sure the get the device manager from the MediaStreamSource, it implements IMFDXGIDeviceManagerSource. You might have to use IQueryInterface manually, if I remember correctly (I played with this about 2-3 years ago). Only surfaces created from that device can be passed down the pipeline. Then do the decoding using D3D11 VA. Finally, create the samples using MediaStreamSample.CreateFromDirect3D11Surface().

There is also a D3D11VA decoder in FFmpeg, but I never managed to activate it. I guess it also does not play nice with getting custom device using the method above. Plus, it did not get any update in 2 years, so it is probably dead anyways.

**Comment by mcosmin222** [comment]
I mean GUIDS such as these

D3D11_DECODER_PROFILE_HEVC_VLD_MAIN vs MFVideoFormat_H265

Yes, I am following that guide ^^
I wasn't aware that MediaStreamSource implements IMFDXGIDeviceManagerSource, I am still trying to link the VideoStreamProperties exposed by winRT to decoder profiles in DXVA. Thanks for that.

I expect this will likely take several months to finish, unless it is much easier than I expect.

**Comment by lukasf** [comment]
Each format can have multiple profiles. Usually only some of the profiles can be HW accelerated. I'd take the FFmpeg codec id plus FFmpeg profile id, instead of MF Guids as source.

**Comment by mcosmin222** [comment]
I will guess that the proper decoder config instance (https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_video_decoder_config) for a profile is the one with no encryption.

So the next assumption will be to figure out the number of surfaces required for the decoder.

**Comment by mcosmin222** [comment]
That's advanced stuff. My first objective is to figure out how to do basic playback.

According to the link we would need at least 4 surfaces for a single buffer.

    Surfaces for reference frames.
    Surfaces for deinterlacing (three surfaces).
    Surfaces that the decoder needs for buffering.

I am not sure how many frames are actually needed for references and buffering.

**Comment by mcosmin222** [comment]
I had a look at this hardwares acceleration support page

https://trac.ffmpeg.org/wiki/HWAccelIntro

It says there directx 11 decoder is supported. Internal but not stand alone. What exactly is the difference between standalone and internal?

**Comment by lukasf** [comment]
If I understand the docs correctly, internal means that the decoder will be used automatically, if it is available. Standalone means that you have to select the decoder explicitly.

However, that is documentation for ffmpeg.exe. Things might be different when using FFmpeg as a library.

**Comment by mcosmin222** [comment]
Interesting. I did find some references to using HWAccel in code as well, using C. 

maybe this is just about adjusting the build correctly 🤔

**Comment by mcosmin222** [comment]
Well, it was worth the try, but ffmpeg won't build when enabling hardware acceleration or dx11va. So i guess nothing really changed on this front.

**Comment by lukasf** [comment]
Which error do you get? I read that for DXVA2, you need to include a special header maintained by VLC team. Unfortunately, there is no description for d3d11va on the HWAccelIntro page.

**Comment by mcosmin222** [comment]
Well actually, I did manage to build with the following setup. Not sure why


    ../../../configure \
        --toolchain=msvc \
        --disable-programs \
        **--enable-d3d11va \**
        --disable-dxva2 \
		--disable-encoders \
		--disable-devices \
		**--enable-hwaccels \**
        --disable-doc \
        --arch=x86_64 \
        --enable-shared \
        --enable-cross-compile \
        --enable-debug \
        --enable-zlib \
        --enable-bzlib \
        --enable-lzma \
        --enable-libxml2 \
        --enable-iconv \
        --target-os=win32 \
        --extra-cflags="-MD -DWINAPI_FAMILY=WINAPI_FAMILY_APP -D_WIN32_WINNT=0x0A00 -DLZMA_API_STATIC" \
        --extra-ldflags="-APPCONTAINER WindowsApp.lib" \
        --pkg-config="$DIR/Libs/Build/pkg-config.exe" \

Interesting. But this doesn't guarantee we actually get hardware decoding. In task manager, it doesn't seem to work up the GPU video processing.

**Comment by lukasf** [comment]
Our get_format() function in FFmpegInteropMSS.cpp will currently filter out HW acceleration formats. You should remove that check and see how it goes.

**Comment by mcosmin222** [comment]
So I inverted the condition, to only take hwaccel formats, and playback does work, there's even some video aberation at the beginning of the file, which was encouraging, but task manager still shows nothing in video decoding...

**Comment by lukasf** [comment]
Digging a bit into [ff_get_format](https://www.ffmpeg.org/doxygen/4.1/decode_8c_source.html#l01326) where the error message comes from:

You can use [avcodec_get_hw_config()](https://www.ffmpeg.org/doxygen/4.1/group__lavc__core.html#ga4f80582a2ea9c0e141de5d6f6152008f) on the AVCodec (get this through AVCodecContext->codec), to get the supported HW decoder configurations. They have a "methods" flag indicating how they are supposed to work and initialize. To me it looks like some require you e.g. to put a [HW device context](https://www.ffmpeg.org/doxygen/4.1/structAVHWDeviceContext.html) into the AVCodecContext instance before opening it.

Fist I thought you might have to implement this all manually. But looks like it is maybe already implemented and you must only call the right methods at the right time: av_hwdevice_ctx_alloc (pass enum type d3d11va), av_hwdevice_ctx_init, etc etc are all there, see docs [here](https://www.ffmpeg.org/doxygen/4.1/hwcontext_8c.html#a11d8c9101c95cdcab3dbc5b4c03dfd4d).

**Comment by mcosmin222** [comment]
Yes. I found something similar on stackoverflow.com

https://stackoverflow.com/questions/5985273/using-ffmpeg-hwaccel-from-c

**Comment by mcosmin222** [comment]
Found an example linked in the links you linked to me. It seems we need to handle copying the frame from GPU to CPU.

I was able to create the hardware context for the codec context.

**Comment by lukasf** [comment]
For some scenarios this would probably be the right thing. But since we want to render the frames, we should instead hand over the GPU samples directly to MF. Otherwise we would lose lots of performance for high res video (we copy GPU->CPU, then MF would later again copy CPU->GPU for rendering).

**Comment by mcosmin222** [comment]
I suppose this is done by using the sample from 3DSurface method mentioned above. About that,so far, ffmpeg  seems to create its own device pointer.

I'm not sure if we're gonna lose that much performance. DirectX supports shared memory buffers, which makes copying data between cpu and GPU extremely fast.

But that is far into the future. I still don't know if this will even work at all, gpu copy or not.

**Comment by lukasf** [comment]
Oh yeah, I forgot about the device pointer. I agree it's still way to go to get even basic HW decoding. Good luck digging further.

**Comment by mcosmin222** [comment]
I managed to break playback ^^, and ffmpeg no longer keeps asking for the get_format. I guess this is progress.

**Comment by lukasf** [comment]
Oh really?! Nice work!!

**Comment by mcosmin222** [comment]
I am still pretty sure I didn't configure the hw context correctly. The decoding is now broken, which means something that I did was right, but it is still not 100% correct. More to dig I guess...

**Comment by mcosmin222** [comment]
OK, I think I finally managed to get the config correctly (at least for methods that require a device context, haven't gotten to those that require hw frame context).
Something is happening in the GPU, I get usage in task manager in video decoder, however, at some point (very fast actually), I get a frame with 0 duration.

**Comment by mcosmin222** [comment]
Actually, the issue is with sws_getContext (disregard the 0 duration frame, that was audio lol), in UncompressVideoSampleProvider.

m_pAvCodecCtx->pix_fmt = AV_PIX_FMT_D3D11
m_OutputPixelFormat = AV_PIX_FMT_NV12 

This returns E_OOM, and somehow puts our decoding in an infinite loop lol.
I tried bypassing the scaler and ended up with a MF error

![image](https://user-images.githubusercontent.com/9284164/89325524-9795cb80-d691-11ea-948b-7669883f0c3f.png)

**Comment by lukasf** [comment]
D3D11 pixel format means that the image data is a pointer to a D3D11 GPU surface. After you copy it to local (CPU) memory, it is most probably NV12, since that is the default video encoding also on the GPU. I am pretty sure that SWS can only handle local memory, so you need to copy from GPU before giving it to sws scaler.

**Comment by lukasf** [comment]
I just found this, maybe it helps:

https://ffmpeg.org/doxygen/4.1/hw__decode_8c_source.html

**Comment by mcosmin222** [comment]
Hmm interesting, the "CPU" frame has format AV_PIX_FMT_P010LE (161).
Which is "
like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, little-endian"

It is like NV12 but not quite, as far as I can tell.
I guess I do need to pass through the SWS, but the format must be determined after the first frame is processed (like we do for audio).

**Comment by lukasf** [comment]
Oh interesting. The format might also depend on the file, some encoders can use 10bit for higher efficiency. Dynamic conversion is probably the way to go. Maybe later we can try to guess the format upfront, to avoid SWS if possible.

**Comment by mcosmin222** [comment]
I got it working!

![image](https://user-images.githubusercontent.com/9284164/89379044-bd58ba00-d6fd-11ea-91f7-6291b1619f93.png)

It still requires some work on the branch, we can switch work to the PR.

**Comment by lukasf** [comment]
Closing this since we have the PR merged already...
