### ISSUE TITLE
FFMpegInteropX 0.9.0 nuget package fail at store compliance

### ISSUE THREAD

**Issue by villagra** [ffmpeginteropx/FFmpegInteropX#204]
The latest nuget packages fail at certification, this is the error report.

Supported API test

FAILED
Supported APIs
Error Found: 
The supported APIs test detected the following errors:

`
API ??0COMException@Platform@@Q$AAA@H@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API. 
API ??0ChangedStateException@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API. 
API ??0Delegate@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0DisconnectedException@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0Exception@Platform@@Q$AAA@H@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0Exception@Platform@@Q$AAA@HP$AAVString@1@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0FailureException@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0InvalidArgumentException@Platform@@Q$AAA@P$AAVString@1@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0InvalidArgumentException@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0NotImplementedException@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0Object@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0OutOfBoundsException@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0OutOfMemoryException@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?AlignedFree@Heap@Details@Platform@@SAXPAX@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?Allocate@Heap@Details@Platform@@SAPAXII@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?AllocateException@Heap@Details@Platform@@SAPAXII@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?CreateException@Exception@Platform@@SAP$AAV12@H@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?CreateValue@Details@Platform@@YGP$AAVObject@2@W4TypeCode@2@PBX@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?EventSourceAdd@Details@Platform@@YG?AVEventRegistrationToken@Foundation@Windows@@PAPAXPAUEventLock@12@P$AAVDelegate@2@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?EventSourceGetTargetArray@Details@Platform@@YGPAXPAXPAUEventLock@12@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?EventSourceGetTargetArrayEvent@Details@Platform@@YGPAXPAXIPBXPA_J@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?EventSourceGetTargetArraySize@Details@Platform@@YGIPAX@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?EventSourceInitialize@Details@Platform@@YGXPAPAX@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?EventSourceRemove@Details@Platform@@YGXPAPAXPAUEventLock@12@VEventRegistrationToken@Foundation@Windows@@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?EventSourceUninitialize@Details@Platform@@YGXPAPAX@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?Free@Heap@Details@Platform@@SAXPAX@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetActivationFactory@Details@Platform@@YGJPAVModuleBase@1WRL@Microsoft@@PAUHSTRING__@@PAPAUIActivationFactory@@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetActivationFactoryByPCWSTR@@YGJPAXAAVGuid@Platform@@PAPAX@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetIBoxArrayVtable@Details@Platform@@YGPAXPAX@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetIBoxVtable@Details@Platform@@YGPAXPAX@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetIidsFn@@YGJHPAKPBU__s_GUID@@PAPAVGuid@Platform@@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetObjectContext@Details@Platform@@YGPAUIUnknown@@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetProxyImpl@Details@Platform@@YGJPAUIUnknown@@ABU_GUID@@0PAPAU3@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetTypeCode@Type@Platform@@SA?AW4TypeCode@2@P$AAV12@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetWeakReference@Details@Platform@@YGPAU__abi_IUnknown@@Q$ADVObject@2@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?InitializeData@Details@Platform@@YAJH@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?ReCreateException@Exception@Platform@@SAP$AAV12@H@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?ReleaseInContextImpl@Details@Platform@@YGJPAUIUnknown@@0@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?ReleaseTarget@ControlBlock@Details@Platform@@AAEXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?ResolveWeakReference@Details@Platform@@YGP$AAVObject@2@ABU_GUID@@PAPAU__abi_IUnknown@@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?TerminateModule@Details@Platform@@YG_NPAVModuleBase@1WRL@Microsoft@@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?ToString@Guid@Platform@@QAAP$AAVString@2@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?ToString@int32@default@@QAAP$AAVString@Platform@@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?ToString@uint32@default@@QAAP$AAVString@Platform@@XZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?UninitializeData@Details@Platform@@YAXH@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_ObjectToString@__abi_details@@YGP$AAVString@Platform@@P$AAVObject@3@_N@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseAccessDeniedException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseCOMException@@YGXJ@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseChangedStateException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseClassNotRegisteredException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseDisconnectedException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseFailureException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseInvalidArgumentException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseInvalidCastException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseNotImplementedException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseNullReferenceException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseObjectDisposedException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseOperationCanceledException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseOutOfBoundsException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseOutOfMemoryException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_WinRTraiseWrongThreadException@@YGXXZ in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_cast_Object_to_String@__abi_details@@YGP$AAVString@Platform@@_NP$AAVObject@3@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_cast_String_to_Object@__abi_details@@YGP$AAVObject@Platform@@P$AAVString@3@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_make_type_id@@YGP$AAVType@Platform@@ABU__abi_type_descriptor@@@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__abi_translateCurrentException@@YGJ_N@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _CxxThrowException in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API __CxxFrameHandler3 in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API __std_exception_copy in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API __std_exception_destroy in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API __std_terminate in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _except_handler4_common in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _purecall in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API memchr in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??0?$codecvt@_WDU_Mbstatet@@@std@@QAE@I@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??1?$codecvt@_WDU_Mbstatet@@@std@@MAE@XZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??4?$_Yarn@D@std@@QAEAAV01@PBD@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??Bid@locale@std@@QAEIXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetCurrentThreadId@platform@details@Concurrency@@YAJXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?GetNextAsyncId@platform@details@Concurrency@@YAIXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?ReportUnhandledError@_ExceptionHolder@details@Concurrency@@AAEXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Addfac@_Locimp@locale@std@@AAEXPAVfacet@23@I@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Assign@_ContextCallback@details@Concurrency@@AAEXPAX@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_CallInContext@_ContextCallback@details@Concurrency@@QBEXV?$function@$$A6AXXZ@std@@_N@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Capture@_ContextCallback@details@Concurrency@@AAEXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Decref@facet@locale@std@@UAEPAV_Facet_base@3@XZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Execute_once@std@@YAHAAUonce_flag@1@P6GHPAX1PAPAX@Z1@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Incref@facet@locale@std@@UAEXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Init@locale@std@@CAPAV_Locimp@12@_N@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_IsCurrentOriginSTA@_ContextCallback@details@Concurrency@@CA_NXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_IsNonBlockingThread@_Task_impl_base@details@Concurrency@@SA_NXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_LogCancelTask@_TaskEventLogger@details@Concurrency@@QAEXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_LogScheduleTask@_TaskEventLogger@details@Concurrency@@QAEX_N@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_LogTaskCompleted@_TaskEventLogger@details@Concurrency@@QAEXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_LogTaskExecutionCompleted@_TaskEventLogger@details@Concurrency@@QAEXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_LogWorkItemCompleted@_TaskEventLogger@details@Concurrency@@QAEXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_LogWorkItemStarted@_TaskEventLogger@details@Concurrency@@QAEXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_New_Locimp@_Locimp@locale@std@@CAPAV123@ABV123@@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Release_chore@details@Concurrency@@YAXPAU_Threadpool_chore@12@@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_ReportUnobservedException@details@Concurrency@@YAXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Reset@_ContextCallback@details@Concurrency@@AAEXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Schedule_chore@details@Concurrency@@YAHPAU_Threadpool_chore@12@@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Throw_C_error@std@@YAXH@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_XGetLastError@std@@YAXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Xbad_function_call@std@@YAXXZ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Xinvalid_argument@std@@YAXPBD@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Xlength_error@std@@YAXPBD@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_Xout_of_range@std@@YAXPBD@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__ExceptionPtrCopy@@YAXPAXPBX@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__ExceptionPtrCopyException@@YAXPAXPBX1@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__ExceptionPtrCreate@@YAXPAX@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__ExceptionPtrCurrentException@@YAXPAX@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__ExceptionPtrDestroy@@YAXPAX@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__ExceptionPtrRethrow@@YAXPBX@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?__ExceptionPtrToBool@@YA_NPBX@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?id@?$codecvt@_WDU_Mbstatet@@@std@@2V0locale@2@A in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?in@?$codecvt@_WDU_Mbstatet@@@std@@QBEHAAU_Mbstatet@@PBD1AAPBDPA_W3AAPA_W@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?out@?$codecvt@_WDU_Mbstatet@@@std@@QBEHAAU_Mbstatet@@PB_W1AAPB_WPAD3AAPAD@Z in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _Cnd_broadcast in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _Cnd_destroy_in_situ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _Cnd_init_in_situ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _Cnd_wait in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _Mtx_destroy_in_situ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _Mtx_init_in_situ in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _Mtx_lock in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _Mtx_unlock in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API _Thrd_hardware_concurrency in msvcp140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ??1_StructuredTaskCollection@details@Concurrency@@QAE@XZ in concrt140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
API ?_RunAndWait@_StructuredTaskCollection@details@Concurrency@@QAG?AW4_TaskCollectionStatus@23@PAV_UnrealizedChore@23@@Z in concrt140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
`

I was using the 0.9.0-pre2 version which works fine and pass certification.
It started failing with version: 0.9.0-pre5 

ps: Thanks a lot for building Nuget packages!

**Comment by mcosmin222** [comment]
This looks like it was build with a /debug build.

**Comment by lukasf** [comment]
Indeed these are the types of errors you see when you run the app cert tool on a debug build. It happened to me as well the first time. After I switched to Release, all was green (I tested this package before upping to NuGet).

**Comment by villagra** [comment]
Just to be sure, I've created a new app, added the pacakges:

    <PackageReference Include="FFmpegInteropX">
      <Version>0.9.0</Version>
    </PackageReference>
    <PackageReference Include="FFmpegInteropX.FFmpegUWP">
      <Version>4.2.200</Version>
    </PackageReference>

Built as release, past the certification kit and I get the same errors:
`
API ??0COMException@Platform@@Q$AAA@H@Z in vccorlib140.dll is not supported for this application type. FFmpegInterop.dll calls this API.
`

Downgrading to 0.9.0-pre2 works fine and passes the certification kit

**Comment by mcosmin222** [comment]
Maybe the nuget is a debug build.

**Comment by jmvillagra** [comment]
@lukasf Could you take a look at the nuget package? I just tried one more time on a different machine with a different project just to be sure and I got the same error. The nuget package uploaded must be a debug build.

**Comment by villagra** [comment]
@lukasf Could you take a look at the nuget package? I just tried one more time on a different machine with a different project just to be sure and I got the same error. The nuget package uploaded must be a debug build.

**Comment by lukasf** [comment]
Hi @villagra, you are right, there is a problem with the 0.9.0 package. Thank you for reporting. Looks like I tested a wrong package on my machine. I got the same errors now after trying again with 0.9.0.

It turned out there was a bug in the new library build script, which made the lib reference VC runtime for desktop instead of VC runtime for UWP. The error messages look very similar to what you get on debug builds, which is why I assumed this first.

I have fixed the script and created a prerelease package 0.9.1-pre. On my PC I do not get WACK errors anymore with this package. Please confirm on your side, then I will make this an official 0.9.1.

**Comment by villagra** [comment]
Thanks a lot @lukasf . I can confirm the fix works great. The store compliance is all green again

**Comment by lukasf** [comment]
Glad to hear that. Official 0.9.1 is available now (binaries are identical to 0.9.1-pre).
