### ISSUE TITLE
Possible to specify framerate?

### ISSUE THREAD

**Issue by mrapitis** [ffmpeginteropx/FFmpegInteropX#211]
I am playing a raw h264 file back that does not contain the framerate.  Using ffmpeg I am able to override the framerate using the -framerate 60 to specify the rate.  Is it possible to pass in a parameter to do the same using the FFmpegInteropX library?

**Comment by mcosmin222** [comment]
There is a way to pass ffmpeg options when creating the media stream source instance by setting them in the ffmpeginteropconfig instance.

**Comment by lukasf** [comment]
Some of these parameters will only work on the CLI interface. I tried setting "framerate" in FFmpegOptions, but it had no effect on normal video files.

Can you upload a sample of your file?

**Comment by mrapitis** [comment]
@lukasf  I have attached a sample video... by default ffmpeg plays the video back at 25 fps which is actually too slow.  The actual framerate should be set to 60 and can be overridden using the framerate 60 command line option.
[sample-video.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/5257203/sample-video.zip)

**Comment by lukasf** [comment]
Thanks for the sample. It does not look like FFmpeg allows us to directly override the frame rate, even if the file does not have a frame rate itself. But I could extend our lib to allow frame rate override. Please check branch "framerate". It allows you to override the framerate in the VideoStreamInfo (this needs to be done before the PlaybackItem is created!). To try it, edit the C# sample and insert `FFmpegMSS.CurrentVideoStream.FramesPerSecondOverride = 60.0` in OpenLocalFile() after creating the FFmpegMSS. Now the file will play at 60fps.

Is this a soultion that would work for you? Do you know the frame rate upfront?

**Comment by mrapitis** [comment]
Right, I know the framerate upfront so this approach will work well for this use case.  Thanks for the framerate branch, I tested your changes and they are working well so far. Really appreciate your help!

**Comment by mrapitis** [comment]
@lukasf your changes are working great, would it be possible to include this fix into an upcoming release? many thanks for your help.

**Comment by lukasf** [comment]
Sure, I will create a PR to get this into the repo.

**Comment by lukasf** [comment]
Hi @mrapitis, this is now available in the master branch.
