### ISSUE TITLE
Can you play it in rtp://?

### ISSUE THREAD

**Issue by takapdayon** [ffmpeginteropx/FFmpegInteropX#212]
I'm thinking of doing local streaming of ffmpeg with rtp.
FFmpegInteropMSS.CreateFromUriAsync("rtp://ip:xxx", Config) does not work.
What should I do?

**Comment by lukasf** [comment]
I tried it myself and frankly I don't know what is going on. FFmpeg opens a connection and waits for header data to come in, but the data never comes (it waits forever in a polling loop). I really don't know what is missing here. First I thought it could be a UWP sandboxing thing, but even if all permissions are there and local loopback is enabled, it still does not work.

**Comment by lukasf** [comment]
Closing this for now...
