### ISSUE TITLE
Some file failed to play

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [ffmpeginteropx/FFmpegInteropX#214]
i use the lib with the following code
```
async Task<MediaPlaybackItem> InitMediaPlaybackItemFFmpeg(StorageFile file)
        {
            if (null == file)
                return null;

            //Get an IRandomAccessStream for the media you want to playback.
            using (IRandomAccessStream iras = await file.OpenAsync(FileAccessMode.Read))
            {
                //Create a new FFmpegInteropMSS object using FFmpegInteropMSS.CreateFromStreamAsync() passing it the stream and optionally a config class instance.
                m_ffmpeg = await FFmpegInteropMSS.CreateFromStreamAsync(iras);
                //Get the MediaPlaybackItem from the Interop object by invoking CreateMediaPlaybackItem()
                var playbackItem = m_ffmpeg.CreateMediaPlaybackItem();

                // It's often useful to save a reference or ID to correlate a particular MediaPlaybackItem with the item from the backing data model.
                // CustomProperties stores serializable types, so here we use the media item's URI as the playback item's unique ID. 
                // You are also free to use your own external dictionary if you want to reference non-serializable types.
                MediaSource ms = playbackItem.Source;
                ms.CustomProperties[MediaItem.MediaItemIdKey] = ItemId;

                // Populate display properties for the item that will be used to automatically update SystemMediaTransportControls when the item is playing.
                var displayProperties = playbackItem.GetDisplayProperties();

                // Populate thumbnail
                if (PreviewImageUri != null)
                    displayProperties.Thumbnail = RandomAccessStreamReference.CreateFromUri(PreviewImageUri);

                // Apply properties to the playback item
                playbackItem.ApplyDisplayProperties(displayProperties);

                return playbackItem;
            }
        }
```
but some file failed with a quickly event "EndOfStream"
![image](https://user-images.githubusercontent.com/53161726/93010003-fd8f4000-f5b9-11ea-9b92-ddb5b5001abf.png)

the media file info. if  more info is needed,  i will be glad to provide ,thank you  

General
Unique ID                   : 230571737515198394707921266847186298860 (0xAD76805931A5B825AF0365626B4E27EC)
Complete name               : G:\Users\gly\The.Siege.1998.720p.DTS.dxva.x264-FLAWL3SS\The.Siege.1998.720p.DTS.dxva.x264-FLAWL3SS.mkv
Format                      : Matroska
Format version              : Version 2
File size                   : 6.50 GiB
Duration                    : 1 h 56 min
Overall bit rate            : 8 013 kb/s
Encoded date                : UTC 2011-01-21 05:44:14
Writing application         : mkvmerge v4.4.0 ('Die Wiederkehr') built on Oct 31 2010 21:52:48
Writing library             : libebml v1.0.0 + libmatroska v1.0.0

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.1
Format settings             : CABAC / 12 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 12 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 1 h 56 min
Bit rate                    : 6 499 kb/s
Width                       : 1 280 pixels
Height                      : 544 pixels
Display aspect ratio        : 2.35:1
Frame rate mode             : Constant
Frame rate                  : 23.976 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.389
Stream size                 : 5.15 GiB (79%)
Writing library             : x264 core 112 r1867 22bfd31
Encoding settings           : cabac=1 / ref=12 / deblock=1:-3:-3 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.20 / mixed_ref=1 / me_range=64 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=6 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / constrained_intra=0 / bframes=11 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=185 / rc=2pass / mbtree=1 / bitrate=6499 / ratetol=1.0 / qcomp=0.70 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=48000 / vbv_bufsize=40000 / nal_hrd=none / ip_ratio=1.40 / aq=1:1.20
Language                    : English
Default                     : Yes
Forced                      : No
Color range                 : Full

Audio
ID                          : 2
Format                      : DTS
Format/Info                 : Digital Theater Systems
Codec ID                    : A_DTS
Duration                    : 1 h 56 min
Bit rate mode               : Constant
Bit rate                    : 1 509 kb/s
Channel(s)                  : 6 channels
Channel layout              : C L R Ls Rs LFE
Sampling rate               : 48.0 kHz
Frame rate                  : 93.750 FPS (512 SPF)
Bit depth                   : 24 bits
Compression mode            : Lossy
Stream size                 : 1.22 GiB (19%)
Language                    : English
Default                     : Yes
Forced                      : No

Text #1
ID                          : 3
Format                      : VobSub
Muxing mode                 : zlib
Codec ID                    : S_VOBSUB
Codec ID/Info               : Picture based subtitle format used on DVDs
Language                    : English
Default                     : Yes
Forced                      : No

Text #2
ID                          : 4
Format                      : VobSub
Muxing mode                 : zlib
Codec ID                    : S_VOBSUB
Codec ID/Info               : Picture based subtitle format used on DVDs
Language                    : French
Default                     : No
Forced                      : No

Text #3
ID                          : 5
Format                      : VobSub
Muxing mode                 : zlib
Codec ID                    : S_VOBSUB
Codec ID/Info               : Picture based subtitle format used on DVDs
Language                    : Dutch
Default                     : No
Forced                      : No

Menu
00:00:00.000                : en:00:00:00.000
00:04:32.105                : en:00:04:32.105
00:07:38.792                : en:00:07:38.792
00:10:06.606                : en:00:10:06.606
00:15:15.164                : en:00:15:15.164
00:18:37.116                : en:00:18:37.116
00:26:13.530                : en:00:26:13.530
00:31:30.222                : en:00:31:30.222
00:35:22.537                : en:00:35:22.537
00:43:58.094                : en:00:43:58.094
00:46:22.488                : en:00:46:22.488
00:50:00.539                : en:00:50:00.539
00:53:43.720                : en:00:53:43.720
00:55:24.488                : en:00:55:24.488
00:58:01.478                : en:00:58:01.478
01:00:46.434                : en:01:00:46.434
01:04:33.870                : en:01:04:33.870
01:10:24.971                : en:01:10:24.971
01:12:42.858                : en:01:12:42.858
01:15:55.176                : en:01:15:55.176
01:19:14.667                : en:01:19:14.667
01:21:41.313                : en:01:21:41.313
01:24:37.990                : en:01:24:37.990
01:29:39.624                : en:01:29:39.624
01:32:02.267                : en:01:32:02.267
01:33:35.443                : en:01:33:35.443
01:39:29.046                : en:01:39:29.046
01:43:07.807                : en:01:43:07.807
01:44:30.389                : en:01:44:30.389
01:49:23.098                : en:01:49:23.098

**Comment by mcosmin222** [comment]
We will need the actual video file.

**Comment by OneFingerCodingWarrior** [comment]
the file is too big, so i use the following command trim the first 2 mins file =

**Comment by OneFingerCodingWarrior** [comment]
the file is too big, so i use the command ffmpeg -i "The.Siege.1998.720p.DTS.dxva.x264-FLAWL3SS.mkv" -ss 00:00:00 -to 00:02:00 -c copy C:\Users\gly\Videos\The.Siege.mkv get the clip file 
but during the trim, i found, if the clip size exceed 4GB, then file cannot be played, otherwise, the file can be played, but with no image, only audio
the following is the OnDrive link
https://1drv.ms/u/s!AgPgf7_IJFN1tScQAUa0zyKmJC0z?e=PJ58Pd

**Comment by lukasf** [comment]
The sample will only be helpful if it shows the exact same behavior as the full file.

Can you try again without the -ss parameter? Since you want to start from beginning, there is no need for a seek command. If the sample file still behaves differently, the only way is to upload the full file.

By the way, does the file play well with ffplay?

**Comment by OneFingerCodingWarrior** [comment]
You guys are so awesome, i remove the -s parameter, then the sample played pretty well, but if the file size exceed 4GB, play still failed.
ffplay can play well, only with a warning, maybe that's the cause
![image](https://user-images.githubusercontent.com/53161726/93092451-0410db00-f6d2-11ea-9c3e-922ef1c030dd.png)
maybe my file is just too old to be played,
i will try to find a way to upload the full file

**Comment by mcosmin222** [comment]
How big is the file?

**Comment by OneFingerCodingWarrior** [comment]
about 6.5GB, but if the sample exceed 4GB has the same behaves, i think 4GB is enough

**Comment by OneFingerCodingWarrior** [comment]
the following OneDrive link contain the sample, it's about 4.07GB, 
https://1drv.ms/u/s!AomfPH5KjhrNiGFsjgbKeRKX3Twj?e=Cmu8p4

**Comment by lukasf** [comment]
For me, the provided 4.07GB sample could be played, but only audio, no video. I think your original file did not play at all, right? Looks like you will have to upload the complete file.

Still, thanks for providing the sample: I could find an improvement for our lib, that will allow the sample to be played with both video and audio. This should also help with other broken/partial files. I will create a PR for this.

**Comment by OneFingerCodingWarrior** [comment]
one good news, i use the latest code, the file can be played well, both 4.07GB sample and the full size file.
but with a bad news, my app still failed to play both files, it looks like i just messed up, i will try to figure out why.
thanks

**Comment by OneFingerCodingWarrior** [comment]
hi guys, i found the cause
`using (IRandomAccessStream iras = await file.OpenAsync(FileAccessMode.Read))`
is it necessary the keep the stream opened ?

**Comment by mcosmin222** [comment]
Yes. The framework will handle closing the stream on its own.

**Comment by OneFingerCodingWarrior** [comment]
That's a great relief， thanks
