### ISSUE TITLE
pull rtmp

### ISSUE THREAD

**Issue by wudelu** [ffmpeginteropx/FFmpegInteropX#224]
Pull RTMP video stream arm architecture, the delay is very high, about 1 minute will automatically exit

**Comment by lukasf** [comment]
I am not an expert in streaming scenarios, and frankly our lib it not very optimized for streaming. You can try to reduce DefaultBufferTimeUri in the config class. It should improve startup times, but you might run into problems if the connection is not stable enough.

**Comment by lukasf** [comment]
And also, if you are using latest master branch (instead of official NuGet versions), you might also run into a different problem (#230). Try setting VideoDecoderMode to AutomaticSystemDecoder in that case, in addition to reducing buffer times.
