### ISSUE TITLE
Is it possible to capture the current frame?

### ISSUE THREAD

**Issue by sdrc2806** [ffmpeginteropx/FFmpegInteropX#232]
I want to take a snapshot while playing video with rtsp. Is it possible?

**Comment by mcosmin222** [comment]
Hi,

There are several options:

1) You can use the our frame grabber API to grab a frame at the exact current timestamp.

2) You can implement media player frame server mode and save the current frame.

https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/play-audio-and-video-with-mediaplayer#use-mediaplayer-in-frame-server-mode

**Comment by lukasf** [comment]
The frame grabber only works with streams that can be seeked, plus it would require a separate connection. I guess it won't work for your scenario. The much better approach would indeed be using frame server mode. You can use it to keep reference of the last rendered frame. Grabbing it should be possible using Win2D: Create a CanvasBitmap from the D3D surface and use one of the SaveAsync methods.

**Comment by sdrc2806** [comment]
thank you~
