### ISSUE TITLE
How to decode h264 packets using FFmpegInteropX

### ISSUE THREAD

**Issue by abhishek-Tt** [ffmpeginteropx/FFmpegInteropX#236]
@lukasf @mcosmin222 @markslwong
Hi, How can I use this for rendering video-frames on Hololens ?? I am receiving frames in encoded H264 packets. How can I decode these packets to render on HoloLens.

please reply asap.

Thanks in advance

**Comment by OneFingerCodingWarrior** [comment]
maybe you can reference the issue#222, i think there is no immediate copy&paste solution

**Comment by lukasf** [comment]
How do you receive your packets? Is it a stream that can be opened? If you can open your stream with ffmpeg.exe cli, chances are good that you can play it with FFmpegInteropX.

Second step is to get actual rendering into your app. You will need a XAML UI with a MediaPlayerElement. Or you do manual rendering using MediaPlayer in FrameServer mode. In the referenced issue, I pasted some links that can get you started.
