### ISSUE TITLE
Issues that suddenly stop

### ISSUE THREAD

**Issue by sdrc2806** [ffmpeginteropx/FFmpegInteropX#238]
Streaming to rtsp.
I've instantiated VideoFrame and I'm playing the video.
The media player will stop after some time.

Make sure it doesn't stop.
I'm going to get a report and try to reconnect when it's stopped. Is it possible?

[Important: Store the FFmpegInteropMSS instance e.g. in a local field, as long as playback is running. If the object is collected by the GC during playback, playback will stop with an error.] => I don't think this is the problem.

help me

public class VideoFrame
    {
        private readonly FFmpegInteropConfig mConfig = new FFmpegInteropConfig();
        private readonly FFmpegInteropConfig mConfigCapture = new FFmpegInteropConfig();

        private MediaPlayerElement mMediaPlayerElement;
        private MediaPlayer mMediaPlayer = new MediaPlayer();

        private readonly string mCameraName;

        public VideoFrame(MediaPlayerElement mediaPlayerElement, string cameraName)
        {
            Debug.Assert(!string.IsNullOrEmpty(cameraName));
            if(string.IsNullOrEmpty(cameraName)) throw new NullReferenceException("아무것도 비어있으면 안됨. null 도");
            mCameraName = cameraName;

            Debug.Assert(mediaPlayerElement != null);
            mMediaPlayerElement = mediaPlayerElement ?? throw new NullReferenceException("null 참조");

            mConfig.FFmpegOptions.Add("rtsp_flags", "prefer_tcp");
            mConfig.FFmpegOptions.Add("stimeout", 100000);

            mConfigCapture.FFmpegOptions.Add("rtsp_flags", "prefer_tcp");
            mConfigCapture.FFmpegOptions.Add("stimeout", 100000);
        }

        public string RtspUrl { get; set; } = string.Empty;

        private FFmpegInteropMSS mFFmpegMSS;
        private FFmpegInteropMSS mFFmpegMSSFrameCapture;

        public async Task StartCameraAsync()
        {
            while (true)
            {
                try
                {
                    mFFmpegMSS = await FFmpegInteropMSS.CreateFromUriAsync(RtspUrl, mConfig);
                    mFFmpegMSS.BufferTime = TimeSpan.Zero;
                    var source = mFFmpegMSS.CreateMediaPlaybackItem();

                    mMediaPlayerElement.Source = source;

                    Debug.WriteLine(LogFormat.Get(LogFormat.ELevel.DEBUG, Thread.CurrentThread.ManagedThreadId, nameof(StartCameraAsync), $"{mCameraName} 카메라 open 성공"));
                    return;
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(LogFormat.Get(LogFormat.ELevel.ERROR, Thread.CurrentThread.ManagedThreadId, nameof(StartCameraAsync), $"{mCameraName} 에러", ex));
                }
            }
        }

        public async Task StartCameraFrameServerAsync()
        {
            while(true)
            {
                try
                {
                    mFFmpegMSSFrameCapture = await FFmpegInteropMSS.CreateFromUriAsync(RtspUrl, mConfigCapture);
                    mFFmpegMSSFrameCapture.BufferTime = TimeSpan.Zero;
                    var sourceFrameCapture = mFFmpegMSSFrameCapture.CreateMediaPlaybackItem();

                    mMediaPlayer.Source = sourceFrameCapture;
                    mMediaPlayer.IsVideoFrameServerEnabled = true;
                    mMediaPlayer.VideoFrameAvailable += MediaPlayerVideoFrameAvailable;
                    mMediaPlayer.Play();

                    Debug.WriteLine(LogFormat.Get(LogFormat.ELevel.DEBUG, Thread.CurrentThread.ManagedThreadId, nameof(StartCameraFrameServerAsync), $"{mCameraName} 프레임 서버 open 성공"));
                    return;
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(LogFormat.Get(LogFormat.ELevel.ERROR, Thread.CurrentThread.ManagedThreadId, nameof(StartCameraFrameServerAsync), $"{mCameraName} 에러", ex));
                }
            }
        }

**Comment by mcosmin222** [comment]
You may need to set the decoder in ffmpeg config to always use system decoders. 
We recently implemented D3D11 decoders and those are causing some issues with streaming.
See the "VideoDecoderMode" property of the configuration class.

**Comment by lukasf** [comment]
I see that you set BufferTime to Zero. Then you should not have any issues with D3D11 decoders, it only occurs when using the MSS buffer. So I don't believe that this is your problem.

When you create an instance of the VideoFrame class, do you store that instance in your app (e.g. in your MainPage)? If you store the MSS in the VideoFrame, but don't store the VideoFrame in your app, playback will stop as soon as the GC runs.

**Comment by lukasf** [comment]
Closing this since there was no response for a long time.
