### ISSUE TITLE
decode frames

### ISSUE THREAD

**Issue by lihongyi1234** [ffmpeginteropx/FFmpegInteropX#246]
hello, I want to fetch SEI buffer, is there any api to get it

**Comment by lukasf** [comment]
Somehow I missed this issue. FFmpegInteropX is a decoding library. There are currently no APIs to access raw stream data, and I am not sure if such an API would fit within the scope of this lib.

If you need such low level access to stream data, it might be better to directly work with the ffmpeg lib, and get the data you need from the AVPackets.
