### ISSUE TITLE
Unrecognized .dll in Unity

### ISSUE THREAD

**Issue by apranvoku** [ffmpeginteropx/FFmpegInteropX#260]
Hello, (apologies if this is a dumb question.)

I'm trying to use this package in Unity, similar to https://github.com/ffmpeginteropx/FFmpegInteropX/issues/253
I've imported all of the dlls as so and designated them to be active in the editor :
![image](https://user-images.githubusercontent.com/14367479/162244031-13135fe3-f654-4413-b8f0-ec751432fbd1.png)
However, when I try to access functions such as
await FFmpegInteropMSS.CreateFromUriAsync("udp://127.0.0.1:9005", configuration);

Nothing is found. (E.G. "The name "FFmpegInteropMSS.CreateFromUriAsync does not exist in the current context.")

Thanks for any help.

Additional Details:
Unity 2020.3.17f1
HoloLens 2
Backend : .NET Standard 2.0

**Comment by apranvoku** [comment]
For some reason when I add the ENABLE_WINMD_SUPPORT guards the code is greyed out, even though I have UWP selected in build settings. I do have the dlls from both packages in the projects as can be seen in the screenshot.

**Comment by lukasf** [comment]
I think you also need the FFmpegInterop.winmd file. It contains the actual API definitions.

**Comment by Baileymnm1999** [comment]
> For some reason when I add the ENABLE_WINMD_SUPPORT guards the code is greyed out, even though I have UWP selected in build settings. I do have the dlls from both packages in the projects as can be seen in the screenshot.

The code will be greyed out unfortunately. The alternative is to build a uwp component referencing ffmpegiterop in visual studio that encapsulates all of your uwp logic and expose a very simple api/function to call so you aren't programming without intellisense in unity.

**Comment by apranvoku** [comment]
I added the winmd file, didn't change anything. Building the uwp component referencing ffmpeg interop may work, but I'm not sure how to do it and without any guarantees it'll work I don't know if it's the best avenue right now. I appreciate your help though.

**Comment by apranvoku** [comment]
Okay, so Baileymnm1999's solution seems to be the way to go, though I'm really not sure how to do it but it will build and function if you use the #if ENABLE_WINMD_SUPPORT guards. Of course it's a huge pain to debug but such is life.
