### ISSUE TITLE
C++/winRT and winUI

### ISSUE THREAD

**Issue by brabebhin** [ffmpeginteropx/FFmpegInteropX#265]
So I have been looking into the future of Windows development, and it seems pretty clear to me now that UWP app model is very much done for, seeing how Microsoft now allows desktop apps in the store, no questions asked.

This means we need to migrate the library to C++/winRT to avoid becoming obsolete ourselves. I know this has been a topic in the past, with mixed results. C++/winRT hasn't evolved much since, unfortunately. The IDL file is still something I regard as a very poor design decision to fix a problem that could have been handled by the compiler (with a key word or something, like C++/CX does it). Oh well..

Microsoft seems to have adopted C++/winRT quite widely even outside of the store applications (most directx12 samples and other modern COM samples are all in C++/winRT), so I guess this is here to stay.

Now, coming back to the IDL file.
The good news is, we don't need to expose IDL files for all our classes. We only need to do it for the public classes we export, which are fortunately not that many. So in regards to this issue, migration to C++/winRT shouldn't be very difficult. I am tempted to do it rather backwards (starting from the c++ files and moving to idl, as opposed to the recommended Microsoft way).

Since I have a bit of free time on my hands, I could try to do it. What do you think @lukasf ?

**Comment by brabebhin** [comment]
I agree, C++/CX is underrated, I think they should have evolved it somehow instead of replacing with C++/winRT.

**Comment by brabebhin** [comment]
So basically my approach to this was among the lines of...

1. Review which classes really have to be runtime classes, and transform those which are internal only to use std::shared_ptr as a means of ref counting. Losing the internal access modifier is quite painful and I could not find anything equivalent to it. 
2. Port those classes to standard C++.
3. Implement the remaining runtime classes

Steps 1 and 2 are done, mostly. There are some pain points in the DirectXInteropHealer function and native buffer for direct buffer access. These may require some reimplementation, but I will leave these for later.

I will proceed with step 3. Aside from the ffmpeg media source itself, these are mostly trivial. Then I will need your help @lukasf  with reviewing and testing.

Unfortunately, the project file we were using can no longer be salvaged, I will revert all the changes that were done to it in the branch. We will also likely require some changes to the pipeline. We can have both the C++/CX and C++/winrt projects for a while in the SLN.

**Comment by MouriNaruto** [comment]
I don't think it's a good time to use WinUI 3 because WinUI 3 don't have MediaPlayerElement control.

But C++/WinRT is nice, I think.

Kenji Mouri

**Comment by brabebhin** [comment]
Unfortunately it's not as straightforward. Apparently, even consuming the c++/winrt from c# requires a project just to create projections. Microsoft really gave up on all the tooling it had just to support the standard.

**Comment by JunielKatarn** [comment]
@brabebhin Porting to C++/WinRT is a very good idea.

I have worked in React Native for Windows and we heavily rely on that library to enable shared code between Desktop and UWP libraries/apps.

It's also Standard C++ which would make contributions easier in the future.

The team developing this library highly recommends using the latest available NuGet dependency.
Let me know if I can help this effort.

**Comment by brabebhin** [comment]
Thanks @JunielKatarn. I plan to finish porting code next week. If you have more xp with c++/winrt gotchas a review would be great.

Thanks.

The branch is called "standard-cpp-migration"

**Comment by JunielKatarn** [comment]
@brabebhin Awesome.

When the branch is ready for review, please tag me on it.

**Comment by sudongg** [comment]
I have tried to use FFmpegInteropX on WinAppSDK(winui3) and played it successfully.
For FFmpegInteropX , MediaPlayerElement is not a necessity. You can use SwapChainPanel for media playback.
And play 60 FPS with the SwapChainPanel without dropped frames.

**Comment by brabebhin** [comment]
Yes, it works, except subtitles.

**Comment by sudongg** [comment]
> Yes, it works, except subtitles.
MediaPlayerElement drop frame problem I use SwapChainPanel , because drop frame problem can't be solved, but subtitle problem can be solved.
You can get the current subtitles through PlaybackItem.TimedMetadataTracks, and use SwapChainPanel + d2d to render subtitles, and you can also use CanvasControl + win2d to render subtitles.

**Comment by brabebhin** [comment]
Rendering correctly with win2D is not quite trivial, as far as i can tell.  Unless there's a trick I've missed all along.

**Comment by sudongg** [comment]
> Rendering correctly with win2D is not quite trivial, as far as i can tell. Unless there's a trick I've missed all along.

Just add Microsoft.Graphics.Win2D package and use CanvasControl (not CanvaControl ), add Draw event to draw subtitles.
I don't know if there is a ready-made win2d package that can implement custom subtitle rendering, but in my case, just displaying subtitles is enough, and it is not difficult to implement a MediaPlayerElement-like subtitle rendering.

**Comment by brabebhin** [comment]
Ah yes, getting them to render bottom center is indeed easy. But it gets much nastier with SSA/ASS.

**Comment by sudongg** [comment]
> Ah yes, getting them to render bottom center is indeed easy. But it gets much nastier with SSA/ASS.

MediaPlayerElement has only minimal support for SSA/ASS.
win2d is very powerful. Using win2d can achieve better SSA/ASS rendering than MediaPlayerElement, but not every application has high requirements for subtitles. Generally, it only needs to support font styles, and it is not necessary to support animation and special effects.

**Comment by touseefbsb** [comment]
> I have tried to use FFmpegInteropX on WinAppSDK(winui3) and played it successfully. For FFmpegInteropX , MediaPlayerElement is not a necessity. You can use SwapChainPanel for media playback. And play 60 FPS with the SwapChainPanel without dropped frames.

Would you be able to provide a sample app with winappSDK and winui3? within the sample solution we could just have another sample project showcasing all features. This way we could compare and see what features are missing in winAppSdk version and how we can overcome that.
Thanks

**Comment by brabebhin** [comment]
Hi all,

It is on my radar to have something that works with winUI, unfortunately, we aim to get full functionalities rather than limited stuff for specific use cases.

The only thing that we are currently missing right now are subtitles. There's more to subtitles than just text in the bottom center of the screen (that's easy to do). There's font styles, custom positioning, multi subtitle support etc. These are not easy to do. Before I embarked on the C++/winRT journey I actually had a look at rendering subs with win2D, and it isn't easy. There are several ways forward, we could continue developing the subtitle engine or we could wait until libass gets a proper build for UWP. This is probably going to take a few months, but I am pretty confident we will have a strong solution that will work across UWP and winUI and desktop. 

When we will have something done, it will be done using C++ for best efficiency.

Thanks.

**Comment by lukasf** [comment]
You can now use the latest FFmpegInteropX (1.1.0-pre12) package with latest prerelease WinUI 3 (WindowsAppSdk 1.2.220902.1-preview1). Check the WinUI sample, which is now included in our codebase. Please note that this currently only works in packaged app projects. And there are a few things that do not work 100% (some bugs on WinUI side, some issues on our side such as slight subtitle flickering). Things will probably get better once WindowsAppSdk 1.2 gets released officially.

**Comment by touseefbsb** [comment]
I think winappsdk has released 1.2 version.

**Comment by lukasf** [comment]
No, stable version is v1.1, v1.2 is preview/experimental (and the new MediaPlayerElement also has some bugs).

https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
