### ISSUE TITLE
Question: Using the Nuget packges can we convert a video file from mp4 to h265 format.

### ISSUE THREAD

**Issue by AbhilashJangir03** [ffmpeginteropx/FFmpegInteropX#266]
1. Using ffmpeg.exe we can directly convert the video formats. like below -
ffmpeg -i input.mp4 output.265
Is there anyway that using the Nugets (FFmpegInteropX) we can convert the formats?

2. is there any way using which we can get video format details.. container.. codec etc..

**Comment by lukasf** [comment]
Hi @AbhilashJangir03, the library currently does not support conversion scenarios. It is possible to use the MediaSource created with FFmpegInteropX with the UWP transcoding APIs. But then, for the encoding part, you can only use the formats and settings supported by the UWP APIs.

When opening a file or stream with FFmpegInteropX, you can use e.g. the VideoStreams and AudioStreams properties to get codec details for every stream in the file. The next version will also add a FormatInfo property for getting the container details.
