### ISSUE TITLE
openssl error standard-cpp-migration branch

### ISSUE THREAD

**Issue by venki-thiyag** [ffmpeginteropx/FFmpegInteropX#271]
Trying to build standard-cpp-migration branch on my Windows 10 system, observing the following error:

> ERROR: openssl not found

I have added the following flags:

> 	--enable-version3
> 	--enable-nonfree

inside FFmpegConfig.sh, because of the following error:

> OpenSSL <3.0.0 is incompatible with the gpl

Any ideas on how to proceed on this?

Build setup:
- Windows 10 x64
- Visual Studio 2019

**Comment by lukasf** [comment]
Closing this. Feel free to re-open if there are any questions.
