### ISSUE TITLE
Wrong branch name in Docker file: 'docker build' fails

### ISSUE THREAD

**Issue by jdembdr** [ffmpeginteropx/FFmpegInteropX#276]
Hi,
During the image creation, the specified branch for git clone in Dockerfile is release-1.0, but these branch does not exist.

`RUN git clone https://github.com/ffmpeginteropx/FFmpegInteropX.git --recursive -branch release-1.0`

following lines fix the problem for me:
```
RUN git clone https://github.com/ffmpeginteropx/FFmpegInteropX.git --recursive 

# Install build tools
RUN cd FFmpegInteropX `
    && git checkout v1.0.0 `
    && powershell .\Build\InstallTools.ps1 `
	&& rd /S /Q C:\$Recycle.Bin
```

tks,

**Comment by lukasf** [comment]
You are right, I forgot to update the dockerfile when bringing this to master branch.
I updated the dockerfile on master now.
