### ISSUE TITLE
VideoFrame to ImageSource

### ISSUE THREAD

**Issue by yhrgsp** [ffmpeginteropx/FFmpegInteropX#283]
hi,
how do i convert VideoFrame to ImageSource?

       FrameGrabber f = await FrameGrabber.CreateFromUriAsync("udp://192.168.1.24:1234");
            while (true)
            {
                VideoFrame frame = await f.ExtractNextVideoFrameAsync();
                Windows.Storage.Streams.IBuffer buffer = frame.PixelData;
                IRandomAccessStream randomAccessStream = buffer.AsStream().AsRandomAccessStream();
                var bitmapImage = new BitmapImage();
                bitmapImage.SetSource(randomAccessStream);
                imageElement.Source = bitmapImage;
                Thread.Sleep(10);
      
            }

the code never continue after the line: bitmapImage.SetSource(randomAccessStream); 

thanks

**Comment by brabebhin** [comment]
```
public static async Task<BitmapImage> GetImageAsync(FrameGrabber mss, TimeSpan position)
        {
            var videoThumbanilData = await mss.ExtractVideoFrameAsync(position, false);
            using (var ms = new InMemoryRandomAccessStream())
            {
                await videoThumbanilData.EncodeAsPngAsync(ms);
                ms.Seek(0);
                BitmapImage img = new BitmapImage();
                await img.SetSourceAsync(ms);

                var origHeight = videoThumbanilData.PixelHeight;
                var origWidth = videoThumbanilData.PixelWidth;
                var ratioX = 250 / (float)origWidth;
                var ratioY = 250 / (float)origHeight;
                var ratio = Math.Min(ratioX, ratioY);
                var newHeight = (int)(origHeight * ratio);
                var newWidth = (int)(origWidth * ratio);

                img.DecodePixelWidth = newWidth;
                img.DecodePixelHeight = newHeight;

                return img;
            }
        }
```

**Comment by yhrgsp** [comment]
> This example also involves some scaling, which you may not need.
> 
> ```
> public static async Task<BitmapImage> GetImageAsync(FrameGrabber mss, TimeSpan position)
>         {
>             var videoThumbanilData = await mss.ExtractVideoFrameAsync(position, false);
>             using (var ms = new InMemoryRandomAccessStream())
>             {
>                 await videoThumbanilData.EncodeAsPngAsync(ms);
>                 ms.Seek(0);
>                 BitmapImage img = new BitmapImage();
>                 await img.SetSourceAsync(ms);
> 
>                 var origHeight = videoThumbanilData.PixelHeight;
>                 var origWidth = videoThumbanilData.PixelWidth;
>                 var ratioX = 250 / (float)origWidth;
>                 var ratioY = 250 / (float)origHeight;
>                 var ratio = Math.Min(ratioX, ratioY);
>                 var newHeight = (int)(origHeight * ratio);
>                 var newWidth = (int)(origWidth * ratio);
> 
>                 img.DecodePixelWidth = newWidth;
>                 img.DecodePixelHeight = newHeight;
> 
>                 return img;
>             }
>         }
> ```

thanks!!!

**Comment by yhrgsp** [comment]
thanks again
