### ISSUE TITLE
Winui 3, cswinrt, and dotNet 5+

### ISSUE THREAD

**Issue by brabebhin** [ffmpeginteropx/FFmpegInteropX#297]
Hi,

So microsoft finally decided to include a Mediaplayerelement in winui 3, this means the primary blocker of using this library in winui 3 has been removed.

However, as there are some other soul withering issues left.

- dotNet 5+ no longer has built in support for cppwinRT components. We need to create a projection assembly to allow consuming this stuff from cs.
- the [bindable] attribute seems to be projected to the old uwp Windows.UI.Xaml.Data namespace. This causes the compilation of the binding project to fail
- MediaElement seems to be obsolete. We should consider removing it.
- we need to distribute the projection assembly as a nuget package.

All in all, it seems we can't easily support WinUi 3 and donet 5+ without some changes to our code base that may make the project incompatible with uwp. 

Unless I'm missing something.

**Comment by lukasf** [comment]
Oh really, they did it?! Wow, I did no expect that, at least not so fast. It's a shame though that WinUI 3 is still not open source. And from the current docs, it looks like they only rebuilt the UI control. It still uses the old MediaPlayer. And that means, even if they'd open-source WinUI 3 at some point, they probably won't open-source the MediaPlayer along with it... :'(

It would be great if we could make our code base work with both WinUI 3 and UWP, so we can distribute only one NuGet package that works on any platform. If it is only the bindable attribute that breaks it, we might consider removing that. I think the attribute is only needed for data binding from C++/CX apps. I'd like to keep that in place, if possible. But if it is the only thing that prevents common NuGet package, we should consider removing it.

I do not see a problem in removing MediaElement.

**Comment by brabebhin** [comment]
Using the old MediaPlayer is good for us, since we kind of built our entire library around that and its related classes.
I am working on the projection assembly on branch dotnet-interop-assembly. I managed to get the build working by removing [bindable] and MediaElement but now I am battling class not registered exceptions.

**Comment by lukasf** [comment]
Closing this since preliminary WinUI support is now available in the prerelease package.
