### ISSUE TITLE
Disposing FFmpegMedisSource may block for a long period of time

### ISSUE THREAD

**Issue by yikuo123** [ffmpeginteropx/FFmpegInteropX#323]
1. Create a `FFmpegMedisSource` instance by `FFmpegMediaSource.CreateFromUriAsync(uri)`
2. Play the media source
3. Seek to any position, and when it is buffering call `ffmpegMedisSource.Dispose()`

It will block for an unknown period of time.

I don't know if it is for design, but it bothered me.

Workaround:

```c#
var ffmpegMedisSource = this.ffmpegMediaSource;
this.ffmpegMediaSource = null;
Task.Run(() => ffmpegMedisSource.Dispose());
```

**Comment by lukasf** [comment]
Streaming souces are usually divided into chunks of data. When seeking and the next sample is requested, the nearest chunk will be read by ffmpeg until the target position inside that chunk was found. It depends on the actual seek position inside the chunk how fast the desired sample is available. Our instance is locked during each sample read, so disposing will only happen after the first sample was read.

There might be a way to interrupt the ffmpeg internal reading. But we cannot simply access our instance without locking. So even if it is possible to interrupt ffmpeg, we'd have to introduce a different locking concept to make this work.

We are working on a new approach where the FFmpegMediaSource will be disposed automatically as soon as playback stops (#320). This is not finished yet, but if it works, you might not have to call Dispose at all. So I am not sure if it makes sense to put much work into faster disposing, when it might be unneccessary at all in future.

**Comment by brabebhin** [comment]
This is probably an issue with URI sources, local playback should be mostly fast enough.
I don't think ffmpeg provides a cancel mechanism so that we can cancel seek or read operations.

**Comment by lukasf** [comment]
There is an AVIOInterruptCB on the AVFormatContext, which we can theoretically use to cancel long running operations. But I need to see if/how we can safely use it when our instance is locked.

**Comment by lukasf** [comment]
Hi @yikuo123, can you please check the branch "fast-dispose" to see if the behavior has been improved?

**Comment by lukasf** [comment]
Closing after merge of #325
