### ISSUE TITLE
FFmpegInteropX crashes on WinUI3

### ISSUE THREAD

**Issue by zjarri** [ffmpeginteropx/FFmpegInteropX#342]
Hello everyone,
I'm trying to get the provided WinUI3 sample to run but it keeps throwing an exception on " Config = new MediaSourceConfig();".

      __System.TypeInitializationException: 'The type initializer for 'WinRT.ActivationFactory`1' threw an exception.'_
      __COMException: Klasse nicht registriert (0x80040154 (REGDB_E_CLASSNOTREG))___ (Class not registered)

The Project uses:
- .NET 7.0
- WindowsAppSDK 1.2
- Community.Toolkit.Mvvm
- Microsoft.Windows.CsWinRT
- FFmpegInteropX 1.1.0-pre3 (since the stable release is not compatible)
- FFmpegInteropX.FFmpegUWP 5.1.100

Im lost in this error message, since im quite new to development. I hope this is the right channel for my question, if not then excuse me.

**Comment by brabebhin** [comment]
Install https://www.nuget.org/packages/Microsoft.VCRTForwarders.140

**Comment by brabebhin** [comment]
Our sample doesn't use mvvm community stuff though.
