### ISSUE TITLE
NuGet package updated for preview version

### ISSUE THREAD

**Issue by Dona278** [ffmpeginteropx/FFmpegInteropX#344]
First, this is an awesome library which is the more stable among others that I've tested, so great job guys.
But I would ask: why the preview version is still 1.1.0-pre38 of 10/20/2022 while the master branch received commit (at this moment 3 weeks ago)?
In short, it is possible to have an updated preview nuget package? 
There are some fixes merged that I need :)

Thanks

**Comment by brabebhin** [comment]
I will upload a new nuget soon.

**Comment by Dona278** [comment]
Awesome! Thank you!

**Comment by Dona278** [comment]
I tried to update but with some errors...

1) I saw that from previous version for net6 the Microsoft.Graphics.Win2D was dropped in favor of Win2D.uwp which already was a dependency of the package, but for UAP framework, so I'm asking if it's correct.

2) Skipping the point 1, I had a build error:
```error NETSDK1130: Microsoft.Graphics.Canvas.winmd cannot be referenced. Referencing a Windows Metadata component directly when targeting .NET 5 or higher is not supported. For more information, see https://aka.ms/netsdk1130```.

3) I tried to add the NuGet package Microsoft.Windows.CsWinRT as mentioned in the link within the previous error message and I can build without errors, but VS can't launch program which instant crash without exception.

What can I do? Thanks

**Comment by lukasf** [comment]
Since WinUI is a native lib, you need to enable native code debugging, to see native exceptions which happen during startup.

You definitely need CsWinRT when using with a C#/WinUI3 app. And you should run the app as "Packaged" app. If you want to run unpackaged, you additionally need [VCRTForwarders](https://www.nuget.org/packages/Microsoft.VCRTForwarders.140) and a bunch of APIs cannot be used in unpackaged apps.

Does the same app work with the older prerelease version?

**Comment by Dona278** [comment]
Before this version (pre40) all works without any sort of these problems. The app is run as unpackaged and already have the VCRTForwarder. The only issues that I've found are "access memory violation" and "hang on dispose with uri streaming" (both fixed). Why now I have to change something due to nuget package update? And it's strange that VS can't launch the app for debug amd instead log a process exit directly.

**Comment by brabebhin** [comment]
There appears to be some problems with that packge yes.
I can't succesfully build with it on neither the sample nor my own app

**Comment by brabebhin** [comment]
The pre41 version should fix the dependencies.

**Comment by Dona278** [comment]
Ok now with the pre41 I can build successfully but I can't figure out why when I try to start debug from VS the app crashes instant. With the same configuration but with pre38 works correctly.

The project has this configuration:
```
<TargetFramework>net7.0</TargetFramework>
<TargetPlatformIdentifier>windows</TargetPlatformIdentifier>
<TargetPlatformVersion>10.0.22621.0</TargetPlatformVersion>
<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
```
And this is a list of nuget dependencies, other than microsoft ones:
```
CommunityToolkit.Mvvm 8.1.0
CommunityToolkit.WinUI 7.1.2
CommunityToolkit.WinUI.UI 7.1.2
FFmpegInteropX 1.1.0-pre41
Microsoft.VCRTForwarders.140 1.0.7
Microsoft.WindowsAppSDK 1.3.230228005-preview1
Microsoft.Windows.SDK.BuildTools 10.0.25330-preview
PInvoke.User32 0.7.124
```
Do you see any sort of incongruence? This trouble makes me a headache..

**Comment by Dona278** [comment]
It works like a charm! Now I will test the waited fixes :D
Thank you very much
