### ISSUE TITLE
TypeLoadException on running on x64

### ISSUE THREAD

**Issue by don-pironet-hatch** [ffmpeginteropx/FFmpegInteropX#351]
Steps to reproduce:

1. Link both NuGet packages latest version
2. Build x64
3. Call FFmpegMediaSource.CreateFromUriAsync method

TypeLoadException is being throwed.

When I build for x86 everything works fine.

**Comment by brabebhin** [comment]
What kind of project do you have?

**Comment by don-pironet-hatch** [comment]
We are building a UWP application.

**Comment by brabebhin** [comment]
Can you try installing the latest preview package?

**Comment by don-pironet-hatch** [comment]
I tried with FFMpegInteropX version 1.1.0-pre42 and FFmpegInteropX.FFmpegUWP 5.1.100 and still have that problem.

**Comment by brabebhin** [comment]
Have you also tried our samples?
