### ISSUE TITLE
Support for .Net 7 WINUI-3 apps

### ISSUE THREAD

**Issue by touseefbsb** [ffmpeginteropx/FFmpegInteropX#360]
I made a new project for win ui 3 and the app is targeted to .Net 7 and when I try to install FFmpegInteropX nuget on it it fails.

    <TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    
Package FFmpegInteropX 1.0.1 is not compatible with net7.0-windows10.0.19041 (.NETCoreApp,Version=v7.0). Package FFmpegInteropX 1.0.1 supports: uap10.0 (UAP,Version=v10.0)

**Comment by brabebhin** [comment]
Use the pre-release package or check out the winUI sample in the repository.

**Comment by touseefbsb** [comment]
Ok I did that and now I was able to install it however I am getting following error : 

Error NETSDK1148 A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly.

and I tried installing latest .Net 7 SDK on my machine as well. maybe because the nuget is based on .Net 6 ? could that be the reason?

**Comment by brabebhin** [comment]
The nuget should work with NET 6. Not sure about 7, and it's unlikely we will support 7 cause it is a short support version. Did you install the package or is the project referenced directly?

**Comment by touseefbsb** [comment]
I installed the package. if downgrading my winui project to .net 6 is the only option then sure I can adjust my solution accordingly. But I was hoping to make it work with .net 7 since all winui nugets and even the template studio project generation creates it with .net 7

**Comment by brabebhin** [comment]
The best way to work with 7 is to reference the project directly and manually up the version number.

**Comment by lukasf** [comment]
This is a WinUI thing. You need to manually specify a higher Windows SDK Ref version in the project file. Check here:

https://platform.uno/docs/articles/features/winapp-sdk-specifics.html

For the version number, use your target SDK version number, and for the last digit use the highest revision you find for that number on NuGet:
https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref

**Comment by brabebhin** [comment]
Yes IIRC you need to do some manual changes to the template VS creates in order to use our library.

**Comment by touseefbsb** [comment]
ok so I have updated my project file like so that I added a new ItemGroup with the 2 FrameworkReference tags and added the latest version of versions as described but it is still failing with the following error :

![image](https://github.com/ffmpeginteropx/FFmpegInteropX/assets/11542189/2dd4767c-0d84-4a6b-a5da-15377c4febc5)

Error : 

![image](https://github.com/ffmpeginteropx/FFmpegInteropX/assets/11542189/8da8f964-956a-4673-8f10-90dd0fcaf833)


the error points to **NETSdkError** in this file **Microsoft.Net.Windows.targets**

![image](https://github.com/ffmpeginteropx/FFmpegInteropX/assets/11542189/36456927-c78c-4ea8-98c8-fb897afb8c65)

**Comment by lukasf** [comment]
Our lib has platform target 10.0.22000.0. I think you must use at least this version (or higher) in your app. I just checked our WinUI sample: It also does not compile if I use a lower target sdk than the lib.

**Comment by touseefbsb** [comment]
Thanks it is building now.

**Comment by lukasf** [comment]
Glad to hear that. You might be able to remove the FrameworkReference thing, since most of the time things work fine without it.
