### ISSUE TITLE
FFmpegInteropX in Unity (UWP / ARM64)

### ISSUE THREAD

**Issue by slice3984** [ffmpeginteropx/FFmpegInteropX#374]
Hello,
i try to get this package to work in a Unity UWP app, in my case I work on a HoloLens2 application which is supposed to use this library to decode incoming H264/5 encoded frames.

I struggle to get this to work for a couple of days now and hope I could get help here, I'm not too familiar about how to get external packages / libs to work in Unity.

My first approach to get it working was to just use the plugin NuGetForUnity, but this already failed attempting to install the [FFmpegInteropX.FFmpegUWP](https://www.nuget.org/packages/FFmpegInteropX.FFmpegUWP) package with the following error:

> Can't find a matching dependency for the NuGet Package FFmpegInteropX.FFmpegUWP 5.1.100 that has a TargetFramework supported by the current Unity Scripting Backend. The NuGet Package supports the following TargetFramework's uap10.0

My second attempt was to compile the FFmpeg libraries [FFmpegInteropX Build Instructions](https://github.com/ffmpeginteropx/FFmpegInteropX/blob/master/README-BUILD.md) and copying the compiled libs over to my Assets > FFmpegUWP > ARM64 folder.

After this I edited the settings of each dll to target UWP with ARM64.

Then I extracted the FFmpegInteropX package and copied over the FFmpegInteropX.winmd and FFmpegInteropX.dll to Assets > Plugins.

Here I modified the dll and configured it as UWP / ARM64 and checking the "Editor" checkbox.
I modified the .WINMD file to use UWP and checked the Editor checkbox in here as well.

After all of this I tried to import FFmpegInteropX into my unity script with a using directive but IntelliSense is unable to find the namespace.

**Comment by brabebhin** [comment]
I am no expert in Unity but i know some people have manged to use this with both unity and hololens. So it's possible. Just don't know exactly how. Maybe stackoverflow is a better place to ask.

**Comment by slice3984** [comment]
Yea, I've seen some issues in here already mentioned my case and managed to get it to work and got hope someone in here could help me to set it up.

**Comment by lukasf** [comment]
I also cannot help with this. I never used Unity and I don't have a Hololens.

There is a stackoverflow question about this:
https://stackoverflow.com/questions/58394152/unity-uwp-how-to-import-dll-nuget-package-references-to-my-project

Otherwise, you could try to ping some of the people from the old issues in this repo. Maybe someone is able to help you.

**Comment by slice3984** [comment]
Thanks for the effort, I think I will try my luck on stackoverflow.
