### ISSUE TITLE
Extend support for UWP x64 Build Architectures.

### ISSUE THREAD

**Issue by CosmicPredator** [ffmpeginteropx/FFmpegInteropX#378]
I get weird COM exceptions when on building my UWP app for x64 architecture. But when I build for x86 architecture, it works smoothly. On x64 bit build, the app sometimes raided "CLASS NOT REGISTERED" error or sometimes even the App crashes without throwing any exceptions.

So, can u figure out the issue?

**Comment by brabebhin** [comment]
What version of the nuget do you use?

**Comment by CosmicPredator** [comment]
> What version of the nuget do you use?

- FFmpegInteropX --version 1.1.0-pre42
- FFmpegInteropX.FFmpegUWP --version 5.1.100

**Comment by brabebhin** [comment]
Ok, try an earlier version of the nuget.

**Comment by CosmicPredator** [comment]
> Ok, try an earlier version of the nuget.

It's works with 5.0.0, but when loading subtitles, the media alone crashes and stops playing (I'm adding external subtitles with `TimedTextSouce` and the media is a `m3u8` playlist).

**Comment by brabebhin** [comment]
I just tried the x64 build using the samples, and it seems to work fine with the FFmpegInteropX.FFmpegUWP --version 5.1.100. TBH there isn't much to be said about this package.

What could cause issues is the FFmpegInteropX --version 1.1.0-pre42. Can you try FFmpegInteropX --version 1.0.1?

**Comment by CosmicPredator** [comment]
> I just tried the x64 build using the samples, and it seems to work fine with the FFmpegInteropX.FFmpegUWP --version 5.1.100. TBH there isn't much to be said about this package.
> 
> What could cause issues is the FFmpegInteropX --version 1.1.0-pre42. Can you try FFmpegInteropX --version 1.0.1?

"Tried from samples" means u build the WinUI3 version, and it works fine for Mee too. But my case is UWP and not WinUI3.

**Comment by brabebhin** [comment]
No, tried from samples as in the MediaPlayerCS file with UWP.

**Comment by CosmicPredator** [comment]
> No, tried from samples as in the MediaPlayerCS sample with UWP.

Can u try playing an m3u8 playlist from url. It was the buggy one for me. (As for your reply, i used the 3xact snippets from that MediaPlayerCS sample)

**Comment by brabebhin** [comment]
I need an m3u8 URL.

**Comment by CosmicPredator** [comment]
> I need an m3u8 URL.

I'm not sure that I can share the link here but, here you go
https://www004.vipanicdn.net/streamhls/6d59b534bed63f3ac8097a6033657c95/ep.1.1677599557.1080.m3u8

**Comment by brabebhin** [comment]
Url seems to work fine ^^
I can push a new nuget out of the current master version but it contains breaking changes.

**Comment by CosmicPredator** [comment]
> Url seems to work fine ^^ I can push a new nuget out of the current master version but it contains breaking changes.

It means, it's not crashing?

**Comment by brabebhin** [comment]
No, not crashing. it plays fine

**Comment by CosmicPredator** [comment]
> No, not crashing. it plays fine

I see, thanks for the time. I hope u push the new nuget soon

**Comment by brabebhin** [comment]
There is a pre50 nuget available.
Be warned that this is a preview of the 2.0.0 release, which contains a bunch of breaking  API changes.
Seeing how you probably are a new adopter, it shouldn't be that bad.

**Comment by CosmicPredator** [comment]
> There is a pre50 nuget available. Be warned that this is a preview of the 2.0.0 release, which contains a bunch of breaking API changes. Seeing how you probably are a new adopter, it shouldn't be that bad.

Lemme try that, thanks
