### ISSUE TITLE
Setting Aspect Ratio

### ISSUE THREAD

**Issue by softworkz** [ffmpeginteropx/FFmpegInteropX#391]
Is there some way to set the aspect ratio for displaying?

I don't mean to a affect the video's aspect ratio, it's just about the presentation, i.e. letterboxed, fill width, fill height, cover - or whatever it's called in different implementations..

**Comment by brabebhin** [comment]
Try https://learn.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacksession.normalizedsourcerect?view=winrt-22621#windows-media-playback-mediaplaybacksession-normalizedsourcerect

**Comment by lukasf** [comment]
MediaTransportControls has a Zoom button, which can be enabled via properties. I think what it does internally is set the Stretch property of MediaPlayerElement, which you could also set manually, in case you roll your own TransportControls.

**Comment by softworkz** [comment]
Yeah, the Stretch property does it. Thanks!
