### ISSUE TITLE
COMException with .NET 8

### ISSUE THREAD

**Issue by Dev-Taehui** [ffmpeginteropx/FFmpegInteropX#408]
```
await FFmpegMediaSource.CreateFromUriAsync(new(videoFilePath));
```

With .NET 8, A COMException is raised with "The data area passed to a system call is too small" message.
It wasn't rasied with .NET 7 and played well with Win2D.

My environment is
OS: Microsoft Windows 11 23H2 (22631.3085) x64
WPF project with .NET 8 with XAML Islands
Windows App SDK v1.4.4
VCRTForwarders DLL 1.0.7 and 1.1.0
FFmpegInteropX 1.1.0-pre50 and FFmpegInteropX.Desktop 2.0.0-pre2

**Comment by brabebhin** [comment]
Hi.
We currently don't support dotnet 8.

**Comment by Dev-Taehui** [comment]
@balazs-adam OK, thanks! I hope that it will be support dotnet 8.
