### ISSUE TITLE
A hame a proble runing Build-FFmpeg.ps1

### ISSUE THREAD

**Issue by paulvlad86** [ffmpeginteropx/FFmpegInteropX#419]
i run the script for the build and i get this error

PS C:\WINDOWS\system32> C:\dezvoltare\FFmpegInteropX\Build-FFmpeg.ps1

Building FFmpegUWP

Timestamp: 20240305_212844

WARNING: NASM not found. Installing...
.\Build\InstallTools.ps1 : The term '.\Build\InstallTools.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At C:\dezvoltare\FFmpegInteropX\Build-FFmpeg.ps1:419 char:5
+     .\Build\InstallTools.ps1 nasm
+     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Build\InstallTools.ps1:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

if i run the scipt InstallTools.ps1  i get the same error

PS C:\WINDOWS\system32> C:\dezvoltare\FFmpegInteropX\Build\InstallTools.ps1

    Directory: C:\dezvoltare\FFmpegInteropX

Mode                 LastWriteTime         Length Name                                                                                                                                        
----                 -------------         ------ ----                                                                                                                                        
d-----          3/5/2024   8:01 PM                Tools                                                                                                                                       

Updating MSYS2 packages...

:: Synchronizing package databases...
 clangarm64 downloading...
 mingw32 downloading...
 mingw64 downloading...
 ucrt64 downloading...
 clang32 downloading...
 clang64 downloading...
 msys downloading...
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [Y/n] 
removing all files from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...

Installing NASM...

curl.exe :   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
At C:\dezvoltare\FFmpegInteropX\Build\InstallTools.ps1:56 char:5
+     curl.exe -SL --output nasm.zip  https://www.nasm.us/pub/nasm/rele ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  % Total    % ...  Time  Current:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

please hel me

**Comment by paulvlad86** [comment]
i tied
![image](https://github.com/ffmpeginteropx/FFmpegInteropX/assets/48295511/3ec39222-0fd7-4a9c-b5b3-b37d42b5ace7)
same problem

**Comment by paulvlad86** [comment]
the problem seem to be because of certificate of the site i added -k  --insecure in this line
curl.exe -SL -k  --insecure --output perl.zip https://strawberryperl.com/download/$PerlVersion/strawberry-perl-$PerlVersion-64bit-portable.zip

**Comment by lukasf** [comment]
I have had similar issues at work today, related to certificate revocation servers not being available. Looks like some of the big certificate authorities have troubles with their servers...
