### ISSUE TITLE
insue on build

### ISSUE THREAD

**Issue by paulvlad86** [ffmpeginteropx/FFmpegInteropX#422]
in run the Build-FFmpeg.ps1 and i gent error 
INAPI_FAMILY_APP" -D"_WIN32_WINNT=0x0A00" -D"NDEBUG"   "..\..\..\..\..\Libs\openssl\ssl\record\tls_pad.c" > ssl\record\libcommon-lib-tls_pad.d 2>&1"
        "lib" /nologo /out:providers\libcommon.lib @C:\Users\user1\AppData\Local\Temp\nmC58.tmp
        IF EXIST .manifest DEL /F /Q .manifest
        IF EXIST libcrypto-3.dll DEL /F /Q libcrypto-3.dll
        cmd /C ""link" /nologo /debug /dll /NODEFAULTLIB:kernel32.lib /APPCONTAINER /APPCONTAINER /nologo /debug @C:\Users\user1\AppData\Local\Temp\nmCA7.tmp /implib:libcrypto.lib || (DEL /Q libcrypto-3.* libcrypto.lib & EXIT 1)"
LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'
Could Not Find C:\dezvoltare\FFmpegInteropX\Intermediate\FFmpegUWP\x86\int\openssl\libcrypto-3.*
NMAKE : fatal error U1077: 'cmd' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.22.27905\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
WARNING: Error occured: nmake  exited with code 2.
Original command line:
nmake
Transcript stopped, output file is C:\dezvoltare\FFmpegInteropX\Intermediate\FFmpegUWP\Build_20240306_221645_x86.log

Time elapsed
00:04:22.6298894

WARNING: Build failed!
PS C:\dezvoltare\FFmpegInteropX>

please help me

**Comment by brabebhin** [comment]
hi

Have you checked the build instructions here?
https://github.com/ffmpeginteropx/FFmpegInteropX/blob/master/README-BUILD.md

Particularly the prerequisites?

Is there a reason you are trying to build ffmpeg from scratch?
If you just need to integrate the ffmpeginteropx project in your sln, you don't need to build ffmpeg for that.

**Comment by paulvlad86** [comment]
I have a video steganography project in python, and I need to modify ffmpeg and the h264 library it uses to be able to hide the message in the video. that's why I test first that I can create a build for ffmpeg, then modify ffmpeg

**Comment by brabebhin** [comment]
Wouldn't it be easier to just issue commands to ffmpeg.exe to do what you need, and use one of the official builds that exist out in the wild?

Our build is pretty niche and aims at satisfying our particular niche use case.  We don't support remuxing/transcoding with ffmpeg APIs in any way.

Even if you do succeed in building ffmpeg dlls, you will need to remake huge parts of our interop library in order to use the ffmpeg dlls in your python code, you're looking at quite the effort here.
