### ISSUE TITLE
Many TrueHD streams playing silent

### ISSUE THREAD

**Issue by softworkz** [ffmpeginteropx/FFmpegInteropX#440]
In fact, those from popular releases are almost always remaining silent, but let's look a some specific videos.
When searching for TrueHD at the [KODI Samples](https://kodi.wiki/view/Samples) page, you can find and download three videos with TrueHD audio:

- TrueHD 7.1 Channel Check.m2ts
- VC-1_23.976_TrueHD.mkv
- Hybrid HDR10Plus DV Sample.mkv

For me, only the first one is working when playing with FFmpegInteropX, the other two remain silent. 
Can you confirm this?

All those files, including the latter two, have working audio when transcoded by our server - which is also just using ffmpeg for transcoding.

**Comment by brabebhin** [comment]
I tested the last one and it indeed does not have sound. 
It uses 32bit PCM, with 96000 sampling rate and 6 audio channels.

Interesting.
MediaStreamSource outright rejects our AudioEncodingProperties object and comes up with "decoder error" before playback event starts

I think the problem is the 32 bit PCM. When we are setting the 

>     encodingProperties.Subtype(outSampleFormat == AV_SAMPLE_FMT_FLT ? MediaEncodingSubtypes::Float() : MediaEncodingSubtypes::Pcm());

it will automatically degrade the BitsPerSample property from 32 which we originally set down to 16.
This will probably contradict the BitRate which is computed using 32 to compute, thus resulting in decoder error.

**Comment by softworkz** [comment]
Thanks a lot for looking into this. Here's a comparison of the audio streams from the three files:

![image](https://github.com/user-attachments/assets/64f29fea-f8da-4446-a8a0-b465ed0c3843)

The first column (blue) is used as "reference", and green/red in the 2nd and 3rd column indicate what's equal or different.

**Comment by softworkz** [comment]
As I'm doing support on similar issues (last level, when it couldn't be resolved by others), I know how annoying it can be when you are spending time and effort on analyzing, just to find out eventually, that it has been due to a defective or invalid media file.

But that's not the case here, the history was as follows:

- Two users reported TrueHD is playing silent on our Xbox beta app (which is using FFmpegItneropx
- Then I tried  locally with my own files having TrueHD streams and they remained silent as well
  but when the audio is forced to be transcoded by the server, it plays (and the server is just using ffmpeg for that.
  => means ffmpeg can basically handle thouse streams
- Before posting about it here, I looked for some  publicly available files with TrueDH, found those three and was even surprised that one of them played with audio.
  
So it's not about those specific files - they are just examples. If you like, I can provide more sample files (privately).

**Comment by brabebhin** [comment]
The problem isn't ffmpeg. It is MF. 
Can you compare the last file from the OP before and after transcoding?

I'm curious if anything changes.
I will need to dig some more into this, probably over the weekend.

**Comment by lukasf** [comment]
> I think the problem is the 32 bit PCM. When we are setting the
> 
> > ```
> > encodingProperties.Subtype(outSampleFormat == AV_SAMPLE_FMT_FLT ? MediaEncodingSubtypes::Float() : MediaEncodingSubtypes::Pcm());
> > ```
> 
> it will automatically degrade the BitsPerSample property from 32 which we originally set down to 16. This will probably contradict the BitRate which is computed using 32 to compute, thus resulting in decoder error.

This just sets the subtype float/pcm. In SetMediaEncodingProperties we set the bits per sample. I have never seen a file with 32 bits pcm. I have seen and tested 24 bits, which is common with HD audio (e.g. 24bit/96khz or 24bit/192khz), but 32 bits? Never seen that, not sure if Windows supports it. It might be a wrong tag on the file. Or it is just not supported by Windows, in that case we should downgrade it to 24 bits in SetMediaEncodingProperties (like we do with float/64).

> EDIT: yepp, if I forcefully set the bits per sample to 16 instead of 32, it will work. More interesting is that sound feels natural, isn't stretched out or fast forwarded which are the usual suspects when bit rates do not match. This means that either the file is broken and reports bits per sample 32 as opposed to 16, or windows doesn't like 32 bit PCM (which TBH I never encountered but anyways), in which case we can fix it using the resampler.

Stretching only happens when the sample rate changes. If we change the bitrate, the resampler will be used to downscale. We should downscale to 24 bits if possible, otherwise the HD signal is basically lost.

**Comment by brabebhin** [comment]
Thanks for pointing out the 24 bit support. Once I fully understand what the problem is I'll likely go down the downgrade path. 

32 bit PCM seems to exist in the ffmpeg universe but winRT doesn't seem to support it as far as I can tell. Maybe some special drivers are needed.

**Comment by lukasf** [comment]
Interesting. All files play fine with sound on my side, with sample app from master branch. Can you confirm that you are getting the decode error with latest FFmpegInteropX build @brabebhin? If that is the case, then this is a device specific problem, where the audio device cannot render 32bit pcm, and no automatic conversion is available (which is unexpected).

**Comment by brabebhin** [comment]
Yes. I tried it in my own player and i had stereo downmix option enabled. With it disabled it plays fine.

**Comment by softworkz** [comment]
Thanks a lot for testing. The primary issue is that it doesn't work on Xbox.

The question now is - on what does it depend: The system audio device or that we have different builds...

Would you be able to zip up your compiled player sample app and send it to me so I can compare?
(hotmail com with my user name would be my address)

**Comment by brabebhin** [comment]
There's 2 bugs here.
1. Setting audio subtype to PCM resets bits per sample from 32 to 16. This is fixed on master by @lukasf  some months ago
2. Settings the stereo downmix option in audio config settings will also mess things up, which is what my PR will fix

Both issues seem to be related to the order in which we populate properties in the media encoding properties.

So unless you are using the stereo downmix option, simply try it out on master, no special builds required.

**Comment by softworkz** [comment]
> There's 2 bugs here.

Ah - I've been a bit skeptical because it plays silent no matter whether stereo downmix is on or off and you said the new PR fixes the downmix issue.

> So unless you are using the stereo downmix option, simply try it out on master, no special builds required.

I don't have a working build except my fork. But I'll just integrate both fixes in ours, as it seems to be clear and straightforward. Will post back the result.

**Comment by brabebhin** [comment]
Yes, you essentially need to put 2 lines from the bottom to the top.

This is how it should look before both fixes are applied

![image](https://github.com/user-attachments/assets/b97249fc-4221-4389-8706-9b28a7aa4281)

And this is after

![image](https://github.com/user-attachments/assets/b9778083-92a2-4c7e-8a53-f38c46e73636)

Notice the 2 lines at the bottom are now at top.

**Comment by brabebhin** [comment]
You know you can always check out this repo directly. :)

**Comment by softworkz** [comment]
I have checked it out (Git repo with 4 remotes and 3 working trees), just don't have a current build of ffmpeg which matches...

**Comment by brabebhin** [comment]
By default this repo uses ffmpeg from nuget. It's essentially plug&play.

**Comment by softworkz** [comment]
Oh, I thought I need to build ffmpeg first, but anyway, I've just been lazy to deal with it :-)

**Comment by softworkz** [comment]
> Yes, you essentially need to put 2 lines from the bottom to the top.
> 
> This is how it should look before both fixes are applied
> 
> ![image](https://private-user-images.githubusercontent.com/9284164/388288507-b97249fc-4221-4389-8706-9b28a7aa4281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNDM0NjcsIm5iZiI6MTczMjE0MzE2NywicGF0aCI6Ii85Mjg0MTY0LzM4ODI4ODUwNy1iOTcyNDlmYy00MjIxLTQzODktODcwNi05YjI4YTdhYTQyODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMjI1MjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmJlMWMzOGYyZDFiZDg0MTA1YjkwZjZhNjFiNjVmOWUzY2NlMGNiN2ZhZjU3MzRiNWUwOWM0NTM0MDkyNzVlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.q5SiUxeeSkSmYWMgGn1Ih2ytRzHteEL5mMtklEYPN1Q)
> 
> And this is after
> 
> ![image](https://private-user-images.githubusercontent.com/9284164/388288593-b9778083-92a2-4c7e-8a53-f38c46e73636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNDM0NjcsIm5iZiI6MTczMjE0MzE2NywicGF0aCI6Ii85Mjg0MTY0LzM4ODI4ODU5My1iOTc3ODA4My05MmEyLTRjN2UtOGE1My1mMzhjNDZlNzM2MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMjI1MjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU5YzU5OWRkY2E4MzNmM2NjZmZhMDFjOTY0NTI5OTI4MGI5Njk5MDQxYThhNzM4MDE3NGJkNTMxODQ5OWY4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.O0HC7AjP7_7QmtesEtMGPkQeLCL-gpU7R1fXnvCgIHY)
> 
> Notice the 2 lines at the bottom are now at top.

Thanks, that was very helpful, because the current version of the file has lots of changes which I don't have... 👍

**Comment by softworkz** [comment]
Fixed and working.

Thank you very much!
