### ISSUE TITLE
Rename and detach repository

### ISSUE THREAD

**Issue by lukasf** [ffmpeginteropx/FFmpegInteropX#72]
As discussed in #70 already, I think it would be a good idea to rename the repository. By giving it a unique name, it is easier to differentiate between our fork and the original.

Additionally, we should remove the "fork status", to prevent misguided PRs to the original project. This is possible through Github Support, and it turns the repo into a full standalone repository.

Both changes are possible without losing history. Github will automatically redirect users from old repo links to the new repo. Merge-back to the original repo is still possible (although unlikely).

Some proposals for new names:

FFmpegInterop-Adv(anced)
FFmpegInterop-Plus
FFmpegInteropX

What do you think? Which names do you prefer (new ideas welcome)?

I like FFmpegInteropX, the eXtended version of FFmpegInterop.

**Comment by touseefbsb** [comment]
FFmpegInteropX seems simplest option so I think we should go with that one.

**Comment by touseefbsb** [comment]
after it being detached we will still be able to access it with the same link ?

**Comment by lukasf** [comment]
All links will be redirected. Also git repos will continue to work, although it is recommended to clone the repo again from the new official URI.

**Comment by lukasf** [comment]
It looks like FFmpegInteropX leads by one vote. So we have a name, right? :)

I found out that it is easy to create a free (open source only) github "organization account" and transfer repos there. So instead of having this under my lukasf account, we could have github.com/FFmpegInteropX which will host all our repos. The main repo would obviously be github.com/FFmpegInteropX/FFmpegInteropX. But besides that, we will soon have a few more, one for each lib that is included into our ffmpeg build (starting with zlib, bzip2 and iconv, see #81). I think it would be good if all required repos (except ffmpeg) are bundled under one account.

**Comment by touseefbsb** [comment]
@lukasf  I agree.

**Comment by ramtinak** [comment]
I vote for FFmpegInteropX

**Comment by lukasf** [comment]
I have done the first steps: The repository has been renamed and moved to the new "FFmpegInteropX" github account! You can see the new address in the title bar. Any old links are automatically redirected to the new address. 

Your local github repositories will continue to work thanks to redirection. But GitHub recommends you to update the path. This can be done by either deleting your local repository and cloning it again, or by using git command line to update the url:

     git remote set-url origin https://github.com/ffmpeginteropx/FFmpegInteropX

The final step is to detach the repository (remove "fork" status). This has been requested and will hopefully be completed soon.

Let me know if there are any issues.

**Comment by pashmak73** [comment]
What about project name and solution name? Are you gonna change that to FFmpegInteropX or not?

**Comment by lukasf** [comment]
I think I will rename the solution file. I am not yet decided on the project file. Currently, it can work as a drop-in replacement for any devs who used the original Microsoft repo. Even the old APIs are all available and working (although mostly deprecated). If we change project file name and namespaces, quite a bunch of changes would be neccessary to even test our solution.

**Comment by lukasf** [comment]
Yay, detaching the repo is finished!

**Comment by mcosmin222** [comment]
Well, for us it will be just a namespace modification. I think this is the best time to remove the deprecated MS APIs. The people using them, if any, would miss out a lot by using them so..

**Comment by MouriNaruto** [comment]
I think we should use more C++/WinRT in the future.

**Comment by mcosmin222** [comment]
Maybe we should close this?

**Comment by mcosmin222** [comment]
I think the problem with c++/winRT is that it requires sdk 1803, which is pretty new.

**Comment by MouriNaruto** [comment]
@mcosmin222 Yes, but I think we should prepare now.

**Comment by lukasf** [comment]
I agree with @mcosmin222 that C++/WinRT is currently not an option anytime soon, due to SDK dependency.

**Comment by lukasf** [comment]
Regarding WinRT: When I first read about this, I was pretty excited, because it is so simple to consume UWP APIs. When I then read the parts about "component creation", I was a bit confused, hoping that this stuff is really needed for "normal programming". After trying it out now, I have to say that I am pretty disappointed. Creating classes is now even more complicated! Instead of two files you now even have to maintain three files: idl file, cpp file and h file. First you create the idl, then you must build the solution, then copy some generated prototype classes and headers into your solution, then implement it. And you have to do that for every class, every UI control (Page), ... Right now I don't believe that I am willing to switch to that model. I can arrange with C++/CX, where at least I can go header-only if I want. The same is impossible with C++/WinRT.

**Comment by mcosmin222** [comment]
While I agree there are quite some annoying this in C++/CX, like string handling, I think it integrates quite nicely with the standard C++. I really don't see the point in creating a new C++/winRT abstraction, they should have just built on top of C++/CX, which is a pretty mature technology by now.

**Comment by lukasf** [comment]
I think the whole pointer and hats stuff is pretty annoying. I really like the clean, C#-like dot syntax of C++/WinRT. But the added big overhead to create classes destroys it for me.

Best would be to combine the two: Use C++/CX way to define classes but have them act like in C++/WinRT (stack-only, dot-syntax). This would not be pure C++ anymore, and it would require compiler extensions like in C++/CX. But for me it would combine the benefits of both worlds (I don't care about pure C++ or not, I don't even like C++ ^^).

**Comment by MouriNaruto** [comment]
https://github.com/Project-Nagisa/Nagisa

Here is an open source UWP app project which uses pure C++. (C++/WinRT and Win32 API)
I hope it can help you.

**Comment by lukasf** [comment]
The only way I could see me using this is with massive code generation, to generate the whole crap from idl files. And I don't feel like setting that all up-

**Comment by MouriNaruto** [comment]
Yes, you needs to write idl files and I can understand you.

But pure C++ is good for compiler to optimize, I think.

**Comment by lukasf** [comment]
I know that C++/WinRT is a bit more efficient than C++/CX. But as long as you only use it for control flow and application logic, it's really not an issue at all. All performance critical stuff is done in native libaries (ffmpeg in our case).

**Comment by MouriNaruto** [comment]
I am agree with you.

**Comment by lukasf** [comment]
I am closing this one. Maybe we will do a FFmpegInteropX 2.0 at some point, which is where we could reorganize the folder structure and drop deprecated APIs. But I think for now we are fine with FFmpegInteropX status.
