### ISSUE TITLE
Subtitle syncing

### ISSUE THREAD

**Issue by mcosmin222** [ffmpeginteropx/FFmpegInteropX#95]
Since everybody is happily working on subtitles stuff, I say we are in a good position to do this.

So here's my idea:

Add property for offset (may be negative or positive) in FfmpegInteropConfig. This should be read-only, and will be used to remember which is the original, unmodified start position.

Expose method with "syncSubtitles" in ffmpegInteropMSS. This method will...

1) Set the property in ffmpegInteropConfig.
2) Adjust the start position of every (external) subtitle (probably be clearing the track and adding the cues again)

Change the start position calculus to take into account the offset. Start position must not be lower than 0.

Then we will have to handle all edge cases...

**Comment by lukasf** [comment]
Agreed, it is a good time to add this!

We could store the original start time in the SampleProvider. Then we can always re-calculate the start offset for every stream correctly. Streams might have different offset. Alternatively, we could have startOffset plus a second field additionalOffset, both would be added to calculate the final position of a sub cue or sample.

Keep in mind that we might also want to change delay of audio tracks. I actually have implemented audio delay already on an experimental branch which adds support for external audio tracks. ;)

I think the delay property in the config class should be public. It is the default delay that is always used. Then we have methods like "ChangeSubtitleDelay" and "ChangeAudioDelay" to re-adjust delays during playback.

**Comment by mcosmin222** [comment]
I agree, it should be public, but read only (i.e no public setter).
Oh, so you mean delaying the entire stream by an offset? I was thinking of delaying each cue by an offset, but I guess both work lol. We still have to keep 2 offset variables, one for start of stream and one for induced offset.

**Comment by lukasf** [comment]
Why not have a public setter for the config class? We can initialize the stream with the offset from the config class, and allow changing it later with methods on the MSS instance.

When I watch english movies and people have strong accent, I usually enable english subs. Only when I do not understand a word or sentence, I look down at the subs - and without delay they might just disappear. So I usually have 0.5s delay configured as default subtitle delay, this works very well for me.

**Comment by mcosmin222** [comment]
Because for external subtitles, you cannot use the same stream offset trickery. So when you change the offset, you need to modify the start position of each cue in the track. That would be tiresome to do in a setter. 

So we have a public Get, with plain old method for set.

**Comment by mcosmin222** [comment]
I commited to branch https://github.com/ffmpeginteropx/FFmpegInteropX/tree/subtitle-sync
I will add more code in the coming days.

**Comment by lukasf** [comment]
We need to do our cue fixing on DispatcherTimer, then things should be fine. We must remove all cues from the stream, update positions, and add them again, all on the timer thread.

**Comment by mcosmin222** [comment]
Yep.
I will do that in the coming days.

**Comment by mcosmin222** [comment]
Anyway, for external subs this was surprisingly easy. 
I also added the UI buttons in CS sample and adjusted the UI a bit. 

There is one problem though. The approach is vulnerable to thread races, even if we do use a mutex. The method returns early, (the timer will run in parallel), and the user may be included to click the button again before it is done. We need some sort of AutoResetEvent here. The method should also probably be an IAsyncOperation.

**Comment by mcosmin222** [comment]
So for internal subtitles we have a problem. 

We remove old cues for memory (yes, I know I came up with the idea). So if we are to delay old cues, they will never show up, since we removed them. So I am guessing this removal of old cues will have to be disposed of. 

There is still the need to handle creation of new cues. I will give these a look sometime later.

**Comment by lukasf** [comment]
Closing this after merge of #96.
