### ISSUE TITLE
External DVD Subtitle

### ISSUE THREAD

**Issue by ramtinak** [ffmpeginteropx/FFmpegInteropX#97]
Hi, I've been testing some subtitle formats. It looks like DVDSubtitle (vobsub) is supported already. 
It's good to add an function to load .idx and .sub file from local storage.

Also I have an request:
I think you should create an wiki/doc page that how this project works. what should we know about. and more extra help.
It's really hard to understand it.

**Comment by mcosmin222** [comment]
IIRC we skipped sub/idk for external subs and decided to use winRT for that. 

About the docs/wiki: you mean how it works at code level?

**Comment by ramtinak** [comment]
I mean for decoding part that how you pass data to ffmpeg or even how can we add more subtitles formats support to this (both internal and external) and more.

all public functions/property is clear and no need to add docs/wiki.

**Comment by mcosmin222** [comment]
We skipped sub/idx cause it required 2 streams, and that is not currently supported. 

The reading of streams is pretty straightforward, we just do some casts to convert an async irandomaccessstream to a sync Istream, and then we use that imterface to read stuff.

Adding support for new formats is pretty trivial, ffmpeg does most of the work unattended. We just expose interfaces for this, and patch up things where needed. Passthroughs are more complicated, and they require industry knowledge, which lukasf has aplenty.

For example, when we added external subs, it was mostly modifying our custom code to not crash when dealing with subs streams. 

I think the best way to understand how it works is to just step through it and ask questions when you do not understand something.

**Comment by lukasf** [comment]
As @mcosmin222 said, we usually do not add any format ourselves. If ffmpeg team decides to add support for a new format (e.g. AV1 decoding will come with ffmpeg 4.2), we just update ffmpeg to latest release and the codec works out-of-the-box.

The only situations where we need to do format parsing ourselves:

1. Hardware acceleration (passthrough): For some formats, we need to parse the packets and rebuild the stream in a format accepted by hardware decoders.

2. Subtitle rendering: FFmpeg supports all text based subtitles by converting them to either SSA/ASS text format, or to ffmpeg bitmaps (for bitmap based subs). So we only need to have parsing for SSA/ASS, plus support for rendering ffmpeg bitmaps, no matter which format the actual sub really has.

If you want to understand how the library works, it is indeed best to just open a file, put breakpoints, and follow the execution flow. First we parse the file and create SampleProviders for each stream (check InitFFmpegContext method). For audio and video, the entry point is always the SampleRequested event (see OnSampleRequested method). Then we check which stream is requested and create a sample from the stream's SampleProvider. Subtitles work a bit different.

__SUB/IDX__

We could add support for SUB/IDX by faking it: We provide a method to add it, just like normal external subs, only with two stream parameters. But internally we do not use ffmpeg, but UWP APIs. Then devs don't have to use UWP APIs but can do all subtitle stuff through our lib.
